/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","promise"],function(a,g){a.Hf=function(){this.Init()};a.b.sa(a.Hf,a.Aj,"oj.FilmStripPagingModel");a.Hf.prototype.Init=function(){a.Hf.u.Init.call(this);this.ie=-1;this.Pf=0;this.yb=-1};a.b.g("FilmStripPagingModel.prototype.Init",{Init:a.Hf.prototype.Init});a.Hf.prototype.SKa=function(a){this.Pf=a};a.Hf.prototype.getPage=function(){return this.ie};a.b.g("FilmStripPagingModel.prototype.getPage",{getPage:a.Hf.prototype.getPage});a.Hf.prototype.setPage=
function(a,c){a=parseInt(a,10);try{var d=this.getPageCount(),e=this.ie,f=this.yb,g=f;c&&c.pageSize&&(g=c.pageSize);if(0===this.Pf&&-1===g)return Promise.resolve();var k=Math.ceil(this.Pf/g);if(0>a||a>k-1)throw Error("JET FilmStrip: Invalid 'page' set: "+a);var l=!1;if(a!=e||g!=f){if(!1===this.handleEvent("beforePage",{page:a,previousPage:e}))return Promise.reject();l=!0}this.ie=a;this.yb=g;var m=this.getPageCount(),r=this;return new Promise(function(c){d!=m&&r.handleEvent("pageCount",{pageCount:m,
previousPageCount:d});l&&r.handleEvent("page",{page:a,previousPage:e});c(null)})}catch(t){return Promise.reject(t)}};a.b.g("FilmStripPagingModel.prototype.setPage",{setPage:a.Hf.prototype.setPage});a.Hf.prototype.getStartItemIndex=function(){return-1===this.ie&&-1===this.yb?-1:this.ie*this.yb};a.b.g("FilmStripPagingModel.prototype.getStartItemIndex",{getStartItemIndex:a.Hf.prototype.getStartItemIndex});a.Hf.prototype.getEndItemIndex=function(){return Math.min(this.getStartItemIndex()+this.yb,this.Pf)-
1};a.b.g("FilmStripPagingModel.prototype.getEndItemIndex",{getEndItemIndex:a.Hf.prototype.getEndItemIndex});a.Hf.prototype.getPageCount=function(){return Math.ceil(this.Pf/this.yb)};a.b.g("FilmStripPagingModel.prototype.getPageCount",{getPageCount:a.Hf.prototype.getPageCount});a.Hf.prototype.totalSize=function(){return this.Pf};a.b.g("FilmStripPagingModel.prototype.totalSize",{totalSize:a.Hf.prototype.totalSize});a.Hf.prototype.totalSizeConfidence=function(){return"actual"};a.b.g("FilmStripPagingModel.prototype.totalSizeConfidence",
{totalSizeConfidence:a.Hf.prototype.totalSizeConfidence});(function(){function b(a){var b=g("\x3cdiv\x3e\x3c/div\x3e");b.text(a);return b[0].innerHTML}function c(a){a.css("-webkit-transform",t).css("-ms-transform",t).css("transform",t)}function d(a,b){a.css("-webkit-transform",b).css("-ms-transform",b).css("transform",b)}a.Pa("oj.ojFilmStrip",g.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{maxItemsPerPage:0,orientation:"horizontal",currentItem:0,arrowPlacement:"adjacent",
arrowVisibility:"auto"},_ComponentCreate:function(){this._super();var b=this.element;b.addClass("oj-filmstrip oj-component").attr("tabindex",0).attr("role","region");b.uniqueId();b=this.options;b.disabled&&a.t.warn(aa);if(b.orientation!==y&&b.orientation!==ha)throw Error(q+b.orientation);if(b.arrowPlacement!==e&&b.arrowPlacement!==X)throw Error(p+b.arrowPlacement);if(b.arrowVisibility!==fa&&b.arrowVisibility!==v&&b.arrowVisibility!==x&&b.arrowVisibility!==h)throw Error(n+b.arrowVisibility);this.tG=
this.eventNamespace+"Touch";this.KN=this.eventNamespace+"Mouse";this.Aha=this.eventNamespace+"Key";this.MZ=this.eventNamespace+"NavArrowHoverable";this.ab(!0)},refresh:function(){this._super();this.ab(!1)},getItemsPerPage:function(){return this.Rv},getPagingModel:function(){return this.Nf},fq:function(){this._super();this.Me&&this.ab(this.Me[0])},dq:function(){this._super();this.Me&&this.ab(this.Me[0])},ab:function(b){b&&!this.Nf&&(this.Nf=new a.Hf);if(this.sC()){this.Me=null;this.Ti="rtl"===this.nd();
this.rs=a.C.hf();var c=this.element,d=this;b?(this.Rv=0,this.mU=function(a){d.lU(a)},this.zs=0,this.ID=-1,this.No=function(){d.Iv()},this.Tj=function(){d.Mg()},this.rs&&(this.x9=function(a){d.wU(a)},this.w9=function(a){d.vU(a)},this.uU=function(a){d.tU(a)},this.hpa()),this.l9=function(a){d.fxa(a)},this.m9=function(a){d.gxa(a)},this.o9=function(a){d.ixa(a)},this.bpa(),this.k9=function(a){d.Fv(a)},this.$oa()):this.Z5();for(var e=c.children(),f=0;f<e.length;f++)a.Components.Eh(e[f]);f=this.Nf;if(b)f.on("page",
this.mU);f.SKa(e.length);this.mFa();if(0<e.length){this.S3();for(f=0;f<e.length;f++)a.Components.tg(e[f]);a.C.bl(c[0],this.Tj)}}else c=!1,this.Me&&(c=this.Me[0]),this.Me=[b||c]},_destroy:function(){this.rs&&(this.eCa(),this.uU=this.w9=this.x9=null);this.VBa();this.o9=this.m9=this.l9=null;this.TBa();this.k9=null;this.Z5();this.Nf.off("page",this.mU);this.No=this.Tj=this.Nf=this.mU=null;var a=this.element;a.removeClass("oj-filmstrip oj-component "+L).removeAttr("tabindex role");a.removeUniqueId();this._super()},
Z5:function(){a.C.zm(this.element[0],this.Tj);this.ID=-1;this.hE&&(clearTimeout(this.hE),this.hE=null);for(var b=this.sJ(),c=0;c<b.length;c++)a.Components.Eh(b[c]);this.T4();this.mT().unwrap();this.PEa();for(c=0;c<b.length;c++)a.Components.tg(b[c])},_setOption:function(b,c,d){var f=this.options,g=!1,k=-1,l=this.Nf,u=l.getPage();switch(b){case "disabled":a.t.warn(aa);break;case "orientation":if(c!==y&&c!==ha)throw Error(q+c);g=f.orientation!=c;break;case "maxItemsPerPage":g=f.maxItemsPerPage!=c;break;
case "arrowPlacement":if(c!==e&&c!==X)throw Error(p+c);g=f.arrowPlacement!=c;break;case "arrowVisibility":if(c!==fa&&c!==v&&c!==x&&c!==h)throw Error(n+c);g=f.arrowVisibility!=c;break;case z:if(f.currentItem!=c&&(k=this.KS(c),0>k||k>=l.getPageCount()))throw Error(s+c);}this._super(b,c,d);switch(b){case z:-1<k&&k!=u&&l.setPage(k)}g&&this.ab(!1)},Mg:function(){if(!this.f4)this.f4=!0,this.S3(!0),this.f4=!1;else if(!this.hE){var a=this;this.hE=setTimeout(function(){a.hE=null;a.Mg()},0)}},vd:function(){return this.options.orientation!==
ha},bD:function(){return this.vd()?this.Ti?"right":"left":"top"},uv:function(){return this.vd()?"width":"height"},sC:function(){var a=document.createElement("div"),b=a.style;b.position="absolute";b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var c=!1;try{c=0<a.offsetWidth&&0<a.offsetHeight}catch(d){}b.removeChild(a);return c},mFa:function(){var a=this.element,b=this.vd(),c=a.children();c.addClass(G).wrap("\x3cdiv class\x3d'"+A+" "+M+"'\x3e\x3c/div\x3e");var d=this.bD();this.vn=
d=a.children().wrapAll("\x3cdiv class\x3d'"+A+" "+N+"' style\x3d'"+d+": 0px;'\x3e\x3c/div\x3e").parent();var f=this.options;f.arrowVisibility!==v&&f.arrowPlacement===e&&(this.SR=d.wrap("\x3cdiv class\x3d'"+A+" oj-filmstrip-content-container'\x3e\x3c/div\x3e").parent());a.addClass(A);b||a.addClass(T);f.arrowVisibility!==v&&0<c.length&&(this.wd=this.Qra(),this.Zj=this.Cra(),this.pV()&&this.MDa())},PEa:function(){var a=this.element,b=this.sJ();this.rEa();this.wd&&(this.$u(this.wd),this.wd=null);this.Zj&&
(this.$u(this.Zj),this.Zj=null);var c=a.children(U+I);c&&c.remove();b.removeClass(G).unwrap().unwrap();this.vn=null;this.SR&&(b.unwrap(),this.SR=null);a.removeClass(A+" "+T)},MDa:function(){this.element.on("mouseenter"+this.MZ,function(a){g(a.currentTarget).hasClass("oj-disabled")||g(a.currentTarget).addClass(L)}).on("mouseleave"+this.MZ,function(a){g(a.currentTarget).removeClass(L)})},rEa:function(){this.element.off(this.MZ)},pV:function(){var a=this.options,b=a.arrowVisibility;return b===x||b===
h&&a.arrowPlacement===X},Nxa:function(){return 0<this.Nf.getPage()},Mxa:function(){var a=this.Nf;return a.getPage()<a.getPageCount()-1},QAa:function(){if(this.Nxa()){var a=this.Nf;a.setPage(a.getPage()-1)}},iAa:function(){if(this.Mxa()){var a=this.Nf;a.setPage(a.getPage()+1)}},i6:function(a,b){this.options.arrowPlacement===e?b.css("visibility",a?"":v):b.parent().css("display",a?"":B)},dFa:function(){if(this.options.arrowVisibility!==v){var a=this.Nf,b=a.getPage(),a=a.getPageCount();this.i6(0!==b,
this.wd);this.i6(b!==a-1,this.Zj)}},Qra:function(){var a=this.element,c=this.vd()?P:da,d=this.x5(c);this.options.arrowPlacement===X?a.append(d):a.prepend(d);var a=b(this.F("labelAccArrowPreviousPage")),e=b(this.F("tipArrowPreviousPage")),c=this.w5(d,c,a,e),f=this;c.on("click",function(){f.QAa()});return c},Cra:function(){var a=this.element,c=this.vd()?C:D,d=this.x5(c);a.append(d);var a=b(this.F("labelAccArrowNextPage")),e=b(this.F("tipArrowNextPage")),c=this.w5(d,c,a,e),f=this;c.on("click",function(){f.iAa()});
return c},x5:function(a){var b=g(document.createElement("div"));b.addClass(I+" "+a);this.options.arrowPlacement===X&&(b.addClass("oj-filmstrip-arrow-container-overlay"),this.pV()&&b.addClass(Q));return b},w5:function(a,b,c,d){var f="\x3cdiv class\x3d'"+J+" oj-default oj-enabled "+b+"' role\x3d'button' tabindex\x3d'-1'";a.append(f+("\x3e\x3cspan class\x3d'oj-filmstrip-arrow-icon "+b+" oj-component-icon'\x3e\x3c/span\x3e\x3c/div\x3e"));b=this.element.attr("id");a=a.children(U+J).eq(0);a.uniqueId();
f=a.attr("id");c&&a.attr("aria-label",c);d&&a.attr("title",d);a.attr("aria-labelledby",f+" "+b);this.We(a);this.Gk(a);this.options.arrowPlacement===e&&this.pV()&&a.addClass(Q);return a},mT:function(){return this.vn.find(U+M)},sJ:function(){return this.vn.find(U+G)},Js:function(){return this.vn.children(U+F)},T4:function(){var a=this.vn;this.Js().css(u,t).css(ba,t);this.mT().css(u,t).css(ba,t);a.css(this.uv(),t)},S3:function(b){this.T4();var c=this.options,d=this.vd(),h=c.maxItemsPerPage,n=1>h,l=this.element,
p=this.mT();if(0>this.ID){var m=this.N7(c.currentItem),m=g(p[m]),r=m.children(U+G);r.css(k,t);a.Components.Kr(r[0]);this.ID=d?m.width():m.height()}m=d?l.width():l.height();c.arrowVisibility!==v&&c.arrowPlacement===e&&(l=l.children(U+I).eq(0),d=d?l.width():l.height(),m-=2*d);this.zs=m;n||(d=Math.max(Math.floor(m/this.ID),1),d<h&&(h=d));h=n?Math.max(Math.floor(m/this.ID),1):h;n=m/h;p.css(u,n+W).css(ba,n+W);n=Math.ceil(p.length/h);r=this.Js();d=!1;l=this.Nf;if(l.getPageCount()!=n||this.Rv!=h||!r||1>
r.length){d=!0;if(b)for(var q=0;q<p.length;q++)a.Components.Eh(p[q]);r&&0<r.length&&p.unwrap();for(q=0;q<p.length;q+=h)p.slice(q,q+h).wrapAll("\x3cdiv class\x3d'"+A+" "+F+"' style\x3d'"+k+": "+B+";' "+f+"\x3d'true'\x3e\x3c/div\x3e");if(b)for(q=0;q<p.length;q++)a.Components.tg(p[q])}r=this.Js();r.css(u,m+W).css(ba,m+W);b=this.SR;this.vn.css(this.uv(),m);b&&b.css(this.uv(),m);b=0;if(c.currentItem||0===c.currentItem)b=this.KS(c.currentItem,h);l.getPageCount()!=n||this.Rv!=h||l.getPage()!=b?l.setPage(b,
{pageSize:h}):d&&(c=l.getPage(),this.lU({previousPage:c,page:c}))},lU:function(a){var b=a.page,c=a.previousPage;a=this.vn;var d=this.Js(),e=this.Nf.yb,f=0>c||c==b||this.Rv!=e;this.Rv=e;e=null;f||(e=g(d[c]));var h=this.bD(),k=g(d[b]),n=k.is(w);n&&this.iX(k);var l=this.sy;-1<c&&!f&&(l=!0,a.css(this.uv(),2*this.zs),b<c&&n&&a.css(h,-this.zs+W),b>c?(e.addClass(R),k.addClass(K)):(e.addClass(S),k.addClass(E)));if(l){var u=this,m=this.sy;m&&0>c&&d.filter(ca).addClass(Z);setTimeout(function(){u.L6(b,c,f,m)},
25)}else this.L6(b,c,f)},L6:function(a,b,e,f){var h=this.vn;e||(this.g4=!0,h.on("transitionend"+this.eventNamespace+" webkitTransitionEnd"+this.eventNamespace,this.No));e?this.Iv():(e=this.Js(),f&&c(e),-1<b?(f=a>b,b=g(e[b]),a=g(e[a]),b.addClass(Z),a.addClass(Z),f?(b.removeClass(R),a.removeClass(K),b.addClass(Y),a.addClass(V)):(b.removeClass(S),a.removeClass(E),b.addClass(H),a.addClass(O))):f&&(a=e.filter(ca),d(a,"translate3d(0, 0, 0)")))},Iv:function(){this.g4=!1;var b=this.vn,d=this.bD();b.off(this.eventNamespace).css(this.uv(),
this.zs).css(d,"0px");d=null;if(a.oe.gM(b[0])||this.Zj&&a.oe.gM(this.Zj[0])||this.wd&&a.oe.gM(this.wd[0]))d=document.activeElement;for(var b=this.Nf.getPage(),e=this.Js(),f=0;f<e.length;f++)f!=b&&this.E9(g(e[f]));e.removeClass(Z+" "+Y+" "+V+" "+H+" "+O);c(e);this.dFa();d&&g(d).is(w)&&(d=this.element,(e=a.oe.Wfa(e[b]))?a.oe.iF(e):a.oe.iF(d[0]));this.KS(this.options.currentItem)!=b&&(b=this.z7(b),-1!==b&&this.option(z,b,{_context:{Ed:!0}}))},N7:function(b){var c=-1,d=this.sJ();if("number"===typeof b)0<=
b&&b<d.length&&(c=b);else if("string"===typeof b&&a.C.eN(b))for(var e=0;e<d.length;e++){var f=d[e].id;if(f&&0<f.length&&f===b){c=e;break}}return c},KS:function(a,b){var c=this.N7(a),d=-1;-1<c&&(void 0===b&&(b=this.Rv),d=Math.floor(c/b));return d},z7:function(a,b,c){var d=this.Nf;void 0===b&&(b=d.getPageCount());return 0<=a&&a<b&&(b=this.sJ(),void 0===c&&(c=this.Rv),a*=c,a<b.length)?(c=b[a].id)&&0<c.length?c:a:-1},E9:function(b){a.Components.lu(b[0]);b.css(k,B).attr(f,"true");b.find(U+G).css(k,B)},
iX:function(b){b.css(k,t).removeAttr(f);b.find(U+G).css(k,t);a.Components.Kr(b[0])},$oa:function(){this.element.on("keydown"+this.Aha,this.k9)},TBa:function(){this.element.off(this.Aha)},bpa:function(){this.element.on("mousedown"+this.KN,this.l9).on("mousemove"+this.KN,this.m9).on("mouseup"+this.KN,this.o9)},VBa:function(){this.element.off(this.KN)},hpa:function(){this.element.on("touchstart"+this.tG,this.x9).on("touchmove"+this.tG,this.w9).on("touchend"+this.tG,this.uU).on("touchcancel"+this.tG,
this.uU)},eCa:function(){this.element.off(this.tG)},Fv:function(a){var b=this.Nf,c=b.getPage(),d=-1;switch(a.keyCode){case g.ui.keyCode.RIGHT:d=this.Ti?c-1:c+1;break;case g.ui.keyCode.LEFT:d=this.Ti?c+1:c-1;break;case g.ui.keyCode.DOWN:d=c+1;break;case g.ui.keyCode.UP:d=c-1;break;case g.ui.keyCode.HOME:d=0;break;case g.ui.keyCode.END:d=b.getPageCount()-1;break;default:return}-1<d&&d<b.getPageCount()&&b.setPage(d);a.preventDefault()},fxa:function(a){this.t6(a.originalEvent)},gxa:function(a){this.s6(a,
a.originalEvent)},ixa:function(){this.r6()},wU:function(a){a=a.originalEvent.touches;1===a.length&&this.t6(a[0])},vU:function(a){this.s6(a,a.originalEvent.touches[0]);(this.Ml||this.jw)&&a.preventDefault()},tU:function(){this.r6()},t6:function(a){if(1<this.Nf.getPageCount()&&!this.g4){this.Ml=!0;this.sy=!1;var b=this.vd();this.zL=b?a.pageX:a.pageY;this.Rda=b?a.pageY:a.pageX}},hya:function(a){var b=this.vd();this.zL=b?a.pageX:a.pageY;this.Rda=b?a.pageY:a.pageX;a=this.bD();var b=this.vn,c=this.Nf,d=
this.Js(),e=1;0<c.getPage()&&(this.iX(g(d[c.getPage()-1])),b.css(a,-this.zs+W),e++);c.getPage()<c.getPageCount()-1&&(this.iX(g(d[c.getPage()+1])),e++);1<e&&b.css(this.uv(),e*this.zs);this.VW=parseInt(b.css(a),10)},s6:function(a,b){if(this.Ml){var c=this.vd(),e=(c?b.pageX:b.pageY)-this.zL;Math.abs((c?b.pageY:b.pageX)-this.Rda)>Math.abs(e)&&(this.jw=this.Ml=!1);if(this.sy){var f=c&&this.Ti?0<e:0>e,h=this.Nf,k=h.getPage();if(f&&k<h.getPageCount()-1||!f&&0<k){var n=this.element[0],u=Math.min(m*(c?n.offsetWidth:
n.offsetHeight),r),p=this.bD(),v=this.vn,n=this.Js();Math.abs(e)>=u?(c=f?k+1:k-1,this.z7(c),k=f?k-1:k+1,-1<k&&k<h.getPageCount()&&this.E9(g(n[k])),f&&-1<k&&(n=parseInt(v.css(p),10),v.css(p,n+this.zs+W)),v.css(this.uv(),2*this.zs),this.Ml=!1,h.setPage(c)):(h=c&&this.Ti?-e:e,h=c?"translate3d("+h+"px, 0, 0)":"translate3d(0, "+h+"px, 0)",d(n.filter(ca),h));this.jw=!0}this.jw&&(a.preventDefault(),a.stopPropagation())}else Math.abs(e)>l&&(this.hya(b),this.sy=!0)}},r6:function(){if(this.Ml&&this.sy){var a=
this.Nf.getPage();this.lU({previousPage:a,page:a})}this.jw=this.sy=this.Ml=!1},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-filmstrip-start-arrow"===a?this.widget().find(U+J+U+P)[0]:"oj-filmstrip-end-arrow"===a?this.widget().find(U+J+U+C)[0]:"oj-filmstrip-top-arrow"===a?this.widget().find(U+J+U+da)[0]:"oj-filmstrip-bottom-arrow"===a?this.widget().find(U+J+U+D)[0]:null},getSubIdByNode:function(a){for(var b=this.getNodeBySubId({subId:"oj-filmstrip-start-arrow"}),
c=this.getNodeBySubId({subId:"oj-filmstrip-end-arrow"}),d=this.getNodeBySubId({subId:"oj-filmstrip-top-arrow"}),e=this.getNodeBySubId({subId:"oj-filmstrip-bottom-arrow"}),f=this.element[0];a&&a!=f;){if(a===b)return{subId:"oj-filmstrip-start-arrow"};if(a===c)return{subId:"oj-filmstrip-end-arrow"};if(a===d)return{subId:"oj-filmstrip-top-arrow"};if(a===e)return{subId:"oj-filmstrip-bottom-arrow"};a=a.parentElement}return null}});var e="adjacent",f="aria-hidden",h="auto",k="display",l=3,m=.33,r=100,t=
"",s="JET FilmStrip: Value of 'currentItem' option not found: ",q="JET FilmStrip: Unsupported value set as 'orientation' option: ",p="Unsupported value set as 'arrowPlacement' option: ",n="Unsupported value set as 'arrowVisibility' option: ",u="flex-basis",v="hidden",w=":hidden",y="horizontal",x="hover",z="currentItem",B="none",D="oj-bottom",C="oj-end",J="oj-filmstrip-arrow",I="oj-filmstrip-arrow-container",Q="oj-filmstrip-arrow-transition",A="oj-filmstrip-container",L="oj-filmstrip-hover",G="oj-filmstrip-item",
M="oj-filmstrip-item-container",F="oj-filmstrip-page",N="oj-filmstrip-pages-container",Z="oj-filmstrip-transition",K="oj-filmstrip-transition-next-newpage-from",R="oj-filmstrip-transition-next-oldpage-from",E="oj-filmstrip-transition-prev-newpage-from",S="oj-filmstrip-transition-prev-oldpage-from",V="oj-filmstrip-transition-next-newpage-to",Y="oj-filmstrip-transition-next-oldpage-to",O="oj-filmstrip-transition-prev-newpage-to",H="oj-filmstrip-transition-prev-oldpage-to",T="oj-filmstrip-vertical",
P="oj-start",da="oj-top",X="overlay",U=".",W="px",ha="vertical",fa="visible",ca=":visible",ba="-webkit-flex-basis",aa="JET FilmStrip: 'disabled' option not supported"})();a.Components.Wa("ojFilmStrip","baseComponent",{properties:{arrowPlacement:{type:"string"},arrowVisibility:{type:"string"},currentItem:{type:"string|number"},disabled:{type:"boolean"},maxItemsPerPage:{type:"number"},orientation:{type:"string"}},methods:{getItemsPerPage:{},getPagingModel:{},refresh:{}},extension:{_widgetName:"ojFilmStrip"}});
a.Components.register("oj-film-strip",a.Components.getMetadata("ojFilmStrip"))});