/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","knockout","promise"],function(a,g){a.Fx={};a.Fx.Zc={viewPath:"text!views/",viewSuffix:".html",modelPath:"viewModels/",initializeMethod:"initialize",disposeMethod:"dispose",activatedHandler:"handleActivated",attachedHandler:"handleAttached",detachedHandler:"handleDetached",bindingsAppliedHandler:"handleBindingsApplied",deactivatedHandler:"handleDeactivated",transitionCompletedHandler:"handleTransitionCompleted"};o_("ModuleBinding.defaults",a.Fx.Zc,a);(function(){function b(b,
c,e,f,h,k,l){var q=c.canAnimate;if(null==q||q.call(c,b)){var s,t;if(q=c.prepareAnimation.call(c,b))s=q.newViewParent,t=q.oldViewParent;var C=s||e;t&&t!==e?d(f,t):C===e&&k(null);C!==e&&g.virtualElements.setDomNodeChildren(C,[]);h(C);var J=Array.prototype.slice.call(C.childNodes),I=!1,Q=function(){I||(I=!0,e!==C&&(m(e,J),a.Components&&(r(J,a.Components.Eh),r(J,a.Components.tg))))},A=k.bind(null,t);b.newViewParent=s;b.oldViewParent=t;b.oldViewNodes=f;b.removeOldView=A;b.insertNewView=Q;var L=function(){A();
Q();l()};return c.animate.call(c,b).then(L,function(){L();a.t.error("ojModule animation promise was rejected")})}}function c(a,b,c){b=b||a;var d=[];c&&a===b&&(c.parentNode.removeChild(c),d.push(c));g.virtualElements.setDomNodeChildren(b,d)}function d(a,b){a.forEach(function(a){b.appendChild(a)})}function e(a,b,c){if(a&&a[b]){var d={element:c[0],valueAccessor:c[1]};2<c.length&&(d.viewModel=c[2],3<c.length&&(d["boolean"===typeof c[3]?"fromCache":"cachedNodes"]=c[3]));return g.ignoreDependencies(a[b],
a,[d])}}function f(b,c,d){if(null!=b&&(c=a.Fx.Zc[c],null!=c&&b&&(c=b[c],"function"===typeof c))){var e=void 0;d&&(e={element:d[0],valueAccessor:d[1]},2<d.length&&(e["boolean"===typeof d[2]?"fromCache":"cachedNodes"]=d[2]));return g.ignoreDependencies(c,b,[e])}}function h(a,b,c){var d=[];for(a=g.virtualElements.firstChild(a);null!=a&&a!=c;a=a.nextSibling)a!=b&&d.push(a);return d}function k(a,b){var c=[],d=g.virtualElements.firstChild(a);l(d,b,function(a){c.push(a)});return c}function l(a,b,c){for(;null!=
a;){var d=g.virtualElements.nextSibling(a),e=a.nodeType;a===b||1!==e&&8!==e||c(a);a=d}}function m(a,b){for(var c=b.length-1;0<=c;c--)g.virtualElements.prepend(a,b[c])}function r(a,b){if(b)for(var c=0;c<a.length;c++)b(a[c])}function t(a){if("string"===typeof a)a=g.utils.parseHtmlFragment(a);else if(window.DocumentFragment?a instanceof DocumentFragment:a&&11===a.nodeType)a=g.utils.arrayPushAll([],a.childNodes);else if(Array.isArray(a))a=g.utils.arrayPushAll([],a);else throw"The View ("+a+") has an unsupported type";
return a}function s(b){return new Promise(function(c,d){require([b],function(a){c(a)},function(c){a.t.error("ojModule failed to load "+b);d(c)})})}function q(a){return a?new Promise(function(b){a.then(b,b)}):a}g.bindingHandlers.ojModule={init:function(p,n,u,v,w){function y(a){if(a!=J)throw A;}function x(a){f(a,"disposeMethod",[p,n])}var z,B,D={},C,J=-1,I,Q;g.utils.domNodeDisposal.addDisposeCallback(p,function(){x(z);for(var a=Object.keys(D),b=0;b<a.length;b++)x(D[a[b]].au)});var A=Error("Promise cancelled because ojModule is fetching new View and ViewModel");
8===p.nodeType&&(g.virtualElements.setDomNodeChildren(p,[]),Q=p.nextSibling);g.computed(function(){J++;var u=0===J,v=g.utils.unwrapObservable,M=v(n()),F,N,Z,K,R,E,S,V;"string"===typeof M?F=M:(F=v(M.name),N=v(M.viewName),Z=v(M.params),K=v(M.viewModelFactory),R=v(M.createViewFunction),E=v(M.cacheKey),S=v(M.lifecycleListener),V=v(M.animation));var v=e(S,"activated",[p,n]),Y,O,H=null==E?null:D[E];if(null!=H)delete D[E],Y=Promise.resolve(H.view),O=Promise.resolve(H.au);else if(null!=K&&(O=g.ignoreDependencies(K.createViewModel,
K,[Z,n])),null==O&&null!=F&&(O=s(a.Fx.Zc.modelPath+F)),null!=O&&(O=O.then(function(a,b){y(a);return b="function"===typeof b?new b(Z):f(b,"initializeMethod",[p,n])||b}.bind(null,J)),null!=R&&(Y=O.then(function(a,b){y(a);if(null==b)throw"createViewFunction option cannot be used when the ViewModel is null";var c=b[R];if(null==c)throw"function specified by the createViewFunction option was not found on the ViewModel";return c.call(b)}.bind(null,J)))),null==Y)if(N=null==N?F:N,null!=N)Y=s(a.Fx.Zc.viewPath+
N+a.Fx.Zc.viewSuffix);else throw Error("View name must be specified");if(null==Y)throw Error("ojModule is missing a View");var T;null!=O&&(T=O.then(function(a,b){y(a);return f(b,"activatedHandler",[p,n])}.bind(null,J)));Promise.all([Y,O,v,T,B]).then(function(v,s){if(v==J){var y=s[0];if(null==y)throw"The module's View was resolved to null";var A=t(y),F=s[1],G=!1,K,M=h(p,I,Q),N=k(p,I);null!=C&&(G=!0,K=M,I||(I=document.createElement("div"),I.className="oj-helper-module-cache",g.virtualElements.prepend(p,
I)));var O=!1,y=function(b){O||(O=!0,G?d(M,I):N.forEach(function(a){g.cleanNode(a)}),c(p,b||p,I),u||(e(S,"detached",[p,n,z,K]),f(z,"detachedHandler",[p,n,K]),e(S,"deactivated",[p,n,z]),f(z,"deactivatedHandler",[p,n])),G?(r(K,a.Components?a.Components.lu:null),D[C]={au:z,view:K}):x(z),z=F,C=E)},R=function(b){b=b||p;m(b,A);var c=null!=H;c&&r(A,a.Components?a.Components.Kr:null);e(S,"attached",[b,n,F,c]);f(F,"attachedHandler",[b,n,c]);if(!c){var d=w.createChildContext(F,void 0,function(a){a.$module=
F;a.$params=Z});l(A[0],I,function(a){g.applyBindings(d,a)});e(S,"bindingsApplied",[b,n,F]);f(F,"bindingsAppliedHandler",[b,n])}},T=function(){e(S,"transitionCompleted",[p,n,F]);f(F,"transitionCompletedHandler",[p,n])};if(null!=V){var Y=b({node:p,valueAccessor:n,isInitial:u,oldViewModel:z,newViewModel:F},V,p,M,R,y,T);B=q(Y)}else B=void 0;B||(y(null),R(null),T())}}.bind(null,J),function(b,c){c!==A&&null!=c&&a.t.error(c)}.bind(null,J))},null,{disposeWhenNodeIsRemoved:p});return{controlsDescendantBindings:!0}}};
g.virtualElements.allowedBindings.ojModule=!0})()});