/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojL10n!ojtranslations/nls/localeElements","ojs/ojmessaging"],function(a,g,b){a.$a={};o_("LocaleData",a.$a,a);a.$a.f_=function(b){a.$a.hR=b};o_("LocaleData.setBundle",a.$a.f_,a);a.$a.mF=function(){return a.$a.PT("firstDay")};o_("LocaleData.getFirstDayOfWeek",a.$a.mF,a);a.$a.WHa=function(){return a.$a.PT("weekendStart")};o_("LocaleData.getWeekendStart",a.$a.WHa,a);a.$a.VHa=function(){return a.$a.PT("weekendEnd")};o_("LocaleData.getWeekendEnd",a.$a.VHa,a);a.$a.jF=function(b){if(null==
b||"abbreviated"!==b&&"narrow"!==b)b="wide";b=a.$a.VS().days["stand-alone"][b];return[b.sun,b.mon,b.tue,b.wed,b.thu,b.fri,b.sat]};o_("LocaleData.getDayNames",a.$a.jF,a);a.$a.pF=function(b){if(null==b||"abbreviated"!==b&&"narrow"!==b)b="wide";b=a.$a.VS().months["stand-alone"][b];return[b["1"],b["2"],b["3"],b["4"],b["5"],b["6"],b["7"],b["8"],b["9"],b["10"],b["11"],b["12"]]};o_("LocaleData.getMonthNames",a.$a.pF,a);a.$a.tha=function(){var b=a.$a.VS().dateFormats["long"].toUpperCase(),c=b.indexOf("M"),
b=b.indexOf("Y");return c<b};o_("LocaleData.isMonthPriorToYear",a.$a.tha,a);a.$a.PT=function(b){var c=a.$a.Kl(),d=a.$a.gva()||"001";b=c.supplemental.weekData[b];d=b[d];void 0===d&&(d=b["001"]);return d};a.$a.VS=function(){var b=a.$a.Kl().main,c,d;for(d in b)if(b.hasOwnProperty(d)){c=b[d];break}return c.dates.calendars.gregorian};a.$a.gva=function(){var b=a.ga.gj();if(b&&(b=b.toUpperCase().split(/-|_/),2<=b.length)){var c=b[1];if(4==c.length){if(3<=b.length)return b[2]}else return c}return null};a.$a.Kl=
function(){var c=a.$a.hR;return c?c:a.oy()?(a.o.assert(void 0!==b,"LocaleElements module must be loaded"),b):{}};a.$a.Hoa=function(a){b=a};a.Aa={};o_("Validation",a.Aa,a);a.Aa.VR={};a.Aa.wX={};a.Aa.R5={};a.Aa.U5={};a.Aa.cH={converter:{name:"oj.ConverterFactory",type:a.xk},validator:{name:"oj.ValidatorFactory",type:a.Ve}};a.Aa.fk=function(b,c){var d;b&&!c?d=a.Aa.mJ(b,a.Aa.VR):b&&c&&(d=a.Aa.Az(b,c,a.Aa.VR,a.Aa.cH.converter));return d};o_("Validation.converterFactory",a.Aa.fk,a);a.Aa.rx=function(b,c){var d;
b&&!c?d=a.Aa.mJ(b,a.Aa.wX):b&&c&&(d=a.Aa.Az(b,c,a.Aa.wX,a.Aa.cH.validator));return d};o_("Validation.validatorFactory",a.Aa.rx,a);a.Aa.Qfa=function(b){return a.Aa.mJ(b,a.Aa.R5)};o_("Validation.getDefaultConverterFactory",a.Aa.Qfa,a);a.Aa.pHa=function(b){return a.Aa.mJ(b,a.Aa.U5)};o_("Validation.getDefaultValidatorFactory",a.Aa.pHa,a);a.Aa.y3=function(b,c){var d=a.Aa.cH.converter;a.Aa.Az(b,c,a.Aa.R5,d);a.Aa.Az(b,c,a.Aa.VR,d)};a.Aa.py=function(b,c){var d=a.Aa.cH.validator;a.Aa.Az(b,c,a.Aa.U5,d);a.Aa.Az(b,
c,a.Aa.wX,d)};a.Aa.Bsa=function(b,c,d){if(c&&!a.Aa.eBa(b,c))throw Error("Factory instance does not implement the methods expected by the factory of type "+d);};a.Aa.mJ=function(b,c){a.o.Rq(b);var d=null;b&&(b=b.toLowerCase(),d=(c[b]||{}).instance||null);return d};a.Aa.eBa=function(b,c){var d=!0,e;a.o.oi(b);a.o.oi(c);for(e in c)if(c.hasOwnProperty(e)&&"function"===typeof c[e]&&!b[e]&&"function"!==typeof b[e]){d=!1;break}return d};a.Aa.Az=function(b,c,d,e){a.o.Rq(b);a.o.oi(c);if(b){var h={};h.instance=
c;a.Aa.Bsa(c,e.type,e.name);d[b.toLowerCase()]=h}};a.xk={CONVERTER_TYPE_NUMBER:"number",CONVERTER_TYPE_DATETIME:"datetime",createConverter:function(){}};o_("ConverterFactory",a.xk,a);a.Ve={VALIDATOR_TYPE_REQUIRED:"required",VALIDATOR_TYPE_REGEXP:"regexp",VALIDATOR_TYPE_NUMBERRANGE:"numberRange",VALIDATOR_TYPE_LENGTH:"length",VALIDATOR_TYPE_DATETIMERANGE:"dateTimeRange",VALIDATOR_TYPE_DATERESTRICTION:"dateRestriction",createValidator:function(){}};o_("ValidatorFactory",a.Ve,a);a.yg=function(a){this.Init(a)};
o_("Converter",a.yg,a);a.b.sa(a.yg,a.b,"oj.Converter");a.yg.prototype.Init=function(b){a.yg.u.Init.call(this);this.Yb=b};a.b.g("Converter.prototype.Init",{Init:a.yg.prototype.Init});a.yg.prototype.Pd=function(){a.o.kd();return null};a.b.g("Converter.prototype.getHint",{Pd:a.yg.prototype.Pd});a.yg.prototype.hl=function(){return this.Yb||{}};a.b.g("Converter.prototype.getOptions",{hl:a.yg.prototype.hl});a.yg.prototype.parse=function(){a.o.kd();return null};a.b.g("Converter.prototype.parse",{parse:a.yg.prototype.parse});
a.yg.prototype.format=function(){a.o.kd();return null};a.b.g("Converter.prototype.format",{format:a.yg.prototype.format});a.yg.prototype.resolvedOptions=function(){var a={};g.extend(a,this.Yb);return a};a.b.g("Converter.prototype.resolvedOptions",{resolvedOptions:a.yg.prototype.resolvedOptions});a.zg=function(b,c){var d=new a.ia(b,c,a.ia.Yc.ERROR);this.Init(d)};o_("ConverterError",a.zg,a);a.zg.prototype=Error();a.zg.prototype.Init=function(a){var b=a.detail,c=a.summary;this.sz=a;this.name="Converter Error";
this.message=b||c};a.b.g("ConverterError.prototype.Init",{Init:a.zg.prototype.Init});a.zg.prototype.nA=function(){return this.sz};a.b.g("ConverterError.prototype.getMessage",{nA:a.zg.prototype.nA});a.Al=function(){this.Init()};o_("NumberConverter",a.Al,a);a.b.sa(a.Al,a.yg,"oj.NumberConverter");a.Al.prototype.Init=function(b){a.Al.u.Init.call(this,b)};a.b.g("NumberConverter.prototype.Init",{Init:a.Al.prototype.Init});a.Al.prototype.format=function(b){return a.Al.u.format.call(this,b)};a.b.g("NumberConverter.prototype.format",
{format:a.Al.prototype.format});a.Al.prototype.parse=function(b){return a.Al.u.parse.call(this,b)};a.b.g("NumberConverter.prototype.parse",{parse:a.Al.prototype.parse});a.Dc=function(a){this.Init(a)};o_("DateTimeConverter",a.Dc,a);a.b.sa(a.Dc,a.yg,"oj.DateTimeConverter");a.Dc.prototype.Init=function(b){a.Dc.u.Init.call(this,b)};a.b.g("DateTimeConverter.prototype.Init",{Init:a.Dc.prototype.Init});a.Dc.prototype.format=function(b){return a.Dc.u.format.call(this,b)};a.b.g("DateTimeConverter.prototype.format",
{format:a.Dc.prototype.format});a.Dc.prototype.CF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isHourInDaySet",{CF:a.Dc.prototype.CF});a.Dc.prototype.BF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isHourInAMPMSet",{BF:a.Dc.prototype.BF});a.Dc.prototype.EF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isMinuteSet",{EF:a.Dc.prototype.EF});a.Dc.prototype.GF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isSecondSet",{GF:a.Dc.prototype.GF});a.Dc.prototype.DF=
function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isMilliSecondSet",{DF:a.Dc.prototype.DF});a.Dc.prototype.HF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isYearSet",{HF:a.Dc.prototype.HF});a.Dc.prototype.FF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isMonthSet",{FF:a.Dc.prototype.FF});a.Dc.prototype.AF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isDaySet",{AF:a.Dc.prototype.AF});a.Dc.prototype.zF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isDayNameSet",
{zF:a.Dc.prototype.zF});a.Dc.prototype.vt=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.calculateWeek",{vt:a.Dc.prototype.vt});a.Dc.prototype.parse=function(b){return a.Dc.u.parse.call(this,b)};a.b.g("DateTimeConverter.prototype.parse",{parse:a.Dc.prototype.parse});a.Dc.prototype.xe=function(b,c){return a.Dc.u.xe.call(this,b,c)};a.b.g("DateTimeConverter.prototype.compareISODates",{xe:a.Dc.prototype.xe});a.Pi=function(){this.Init()};o_("Validator",a.Pi,a);a.b.sa(a.Pi,a.b,"oj.Validator");
a.Pi.prototype.Init=function(){a.Pi.u.Init.call(this)};a.b.g("Validator.prototype.Init",{Init:a.Pi.prototype.Init});a.Pi.prototype.validate=function(){a.o.kd()};a.b.g("Validator.prototype.validate",{validate:a.Pi.prototype.validate});a.Pi.prototype.Pd=function(){a.o.kd()};a.b.g("Validator.prototype.getHint",{Pd:a.Pi.prototype.Pd});a.Fk=function(b,c){var d=new a.ia(b,c,a.ia.Yc.ERROR);this.Init(d)};o_("ValidatorError",a.Fk,a);a.Fk.prototype=Error();a.Fk.prototype.Init=function(a){var b=a.detail,c=a.summary;
this.sz=a;this.name="Validator Error";this.message=b||c};a.b.g("ValidatorError.prototype.Init",{Init:a.Fk.prototype.Init});a.Fk.prototype.nA=function(){return this.sz};a.b.g("ValidatorError.prototype.getMessage",{nA:a.Fk.prototype.nA});a.Hm=function(a){this.Init(a)};o_("DateRestrictionValidator",a.Hm,a);a.b.sa(a.Hm,a.Pi,"oj.DateRestrictionValidator");a.Hm.prototype.Init=function(b){a.Hm.u.Init.call(this);this.isa=b.dayFormatter;this.Rc=a.Na.getConverterInstance(b.converter);b&&(this.Nza=b.messageSummary||
null,this.Mza=b.messageDetail||null)};a.b.g("DateRestrictionValidator.prototype.Init",{Init:a.Hm.prototype.Init});a.Hm.prototype.Yxa=function(a){var b=this.isa;return b?(a=b({fullYear:a.fullYear,month:a.month+1,date:a.date}))&&a.disabled:!1};a.Hm.prototype.validate=function(b){var c="",d="",d=a.ta,c=this.Nza,e=this.Mza,h=b?this.Rc.format(b):b,f=b?a.Na._dateTime(b,["fullYear","month","date"],!0):null;if(null===b)return b;if(this.Yxa(f))throw c=c?d.Nc(c,{value:h}):d.F("oj-validator.restriction.date.messageSummary",
{value:h}),d=e?d.Nc(e,{value:h}):d.F("oj-validator.restriction.date.messageDetail",{value:h}),new a.Fk(c,d);return b};a.b.g("DateRestrictionValidator.prototype.validate",{validate:a.Hm.prototype.validate});a.Hm.prototype.Pd=function(){return null};a.b.g("DateRestrictionValidator.prototype.getHint",{Pd:a.Hm.prototype.Pd});a.bo=function(a){this.Init(a)};o_("DateTimeRangeValidator",a.bo,a);a.b.sa(a.bo,a.Pi,"oj.DateTimeRangeValidator");a.bo.prototype.Init=function(b){a.bo.u.Init.call(this);this.Rc=a.Na.getConverterInstance(b.converter);
this.Zi=b.min||null;this.Yj=b.max||null;b&&(this.uD=b.hint||{},this.JC=b.messageSummary||{},this.IC=b.messageDetail||{})};a.b.g("DateTimeRangeValidator.prototype.Init",{Init:a.bo.prototype.Init});a.bo.prototype.validate=function(b){var c=this.JC,d=this.IC,e=d.rangeOverflow,d=d.rangeUnderflow,h=c.rangeOverflow,c=c.rangeUnderflow,f=a.Na,g=this.Zi,p=this.Yj,n="",u="",v=a.ta,w=null,w=b?this.Rc.format(b):b,y,x;if(null===b)return b;w=this.Rc.format(b);g&&(g=f._minMaxIsoString(g,b),y=this.Rc?this.Rc.format(g):
g);p&&(p=f._minMaxIsoString(p,b),x=this.Rc?this.Rc.format(p):p);if(null!==g&&null!==p){if(0<=this.Rc.xe(b,g)&&0>=this.Rc.xe(b,p)||0<this.Rc.xe(g,p))return b}else if(null!==g){if(0<=this.Rc.xe(b,g))return b}else if(null===p||0>=this.Rc.xe(b,p))return b;null!==p&&0<this.Rc.xe(b,p)?(w={value:w,max:x},n=h?h:v.F("oj-validator.range.datetime.messageSummary.rangeOverflow"),u=e?v.Nc(e,w):v.F("oj-validator.range.datetime.messageDetail.rangeOverflow",w)):null!==g&&0>this.Rc.xe(b,g)&&(w={value:w,min:y},n=c?
c:v.F("oj-validator.range.datetime.messageSummary.rangeUnderflow"),u=d?v.Nc(d,w):v.F("oj-validator.range.datetime.messageDetail.rangeUnderflow",w));throw new a.Fk(n,u);};a.b.g("DateTimeRangeValidator.prototype.validate",{validate:a.bo.prototype.validate});a.bo.prototype.Pd=function(){var b=null,c=this.uD,d=c.inRange,e=c.min,c=c.max,h=this.Zi,f=this.Yj,g=h&&this.Rc?this.Rc.format(h):h,p=f&&this.Rc?this.Rc.format(f):f,n=null,u=a.ta;null!==h&&null!==f?(n={min:g,max:p},b=d?u.Nc(d,n):u.F("oj-validator.range.datetime.hint.inRange",
n)):null!==h?(n={min:g},b=e?u.Nc(e,n):u.F("oj-validator.range.datetime.hint.min",n)):null!==f&&(n={max:p},b=c?u.Nc(c,n):u.F("oj-validator.range.datetime.hint.max",n));return b};a.b.g("DateTimeRangeValidator.prototype.getHint",{Pd:a.bo.prototype.Pd});a.Na={};o_("IntlConverterUtils",a.Na,a);a.Na.isoToDate=function(a){return d.isoToDate(a)};a.Na.isoToLocalDate=function(a){return d.isoToLocalDate(a)};a.Na.dateToLocalIso=function(a){return d.dateToLocalIso(a)};a.Na.J8=function(a){return d.J8(a)};a.Na.getLocalTimeZoneOffset=
function(){return d.getLocalTimeZoneOffset()};a.Na.getConverterInstance=function(b){var c="",d={},e=null;b&&("object"===typeof b&&(b instanceof a.yg||b.parse&&"function"===typeof b.parse||b.format&&"function"===typeof b.format?e=b:(c=b.type,d=b.options||{})),e||(c=c||b)&&"string"===typeof c&&(b=a.Aa.fk(c),e=b.createConverter(d)));return e};a.Na._minMaxIsoString=function(a,b){if(a){b=b||this.dateToLocalIso(new Date);var c=b.indexOf("T");0===a.indexOf("T")&&0<c&&(a=b.substring(0,c)+a)}return a};a.Na.ny=
function(b,c){a.o.oi(c);var d="",e="",h=c.propertyName,f;"optionTypesMismatch"===b?(e=c.requiredPropertyName,f=c.requiredPropertyValueValid,d=a.ta.F("oj-converter.optionTypesMismatch.summary",{propertyName:h,propertyValue:c.propertyValue,requiredPropertyName:e}),e=a.Na.zJ(e,f)):"optionTypeInvalid"===b?(h=c.propertyName,f=c.propertyValueValid,d=a.ta.F("oj-converter.optionTypeInvalid.summary",{propertyName:h}),e=a.Na.zJ(h,f)):"optionOutOfRange"===b?(d=a.ta.F("oj-converter.optionOutOfRange.summary",
{propertyName:h,propertyValue:c.propertyValue}),f=c.propertyValueValid,e=a.Na.zJ(h,f)):"optionValueInvalid"===b&&(d=a.ta.F("oj-converter.optionValueInvalid.summary",{propertyName:h,propertyValue:c.propertyValue}),f=c.propertyValueHint,e=a.Na.zJ(h,f));return new a.zg(d,e)};a.Na.zJ=function(b,c){var d;return c?("string"===typeof c?d="oj-converter.optionHint.detail":(d="oj-converter.optionHint.detail-plural",c=c.join(a.ta.F("oj-converter.plural-separator"))),a.ta.F(d,{propertyName:b,propertyValueValid:c})):
""};a.Na.YLa=function(){return""};a.Na._copyTimeOver=function(a,b){return d._copyTimeOver(a,b)};a.Na._clearTime=function(a){return d._clearTime(a)};a.Na._dateTime=function(a,b,c){return d._dateTime(a,b,c)};a.Na._normalizeIsoString=function(a){return d._normalizeIsoString(a)};a.Db=function(a){this.Init(a)};o_("IntlDateTimeConverter",a.Db,a);a.b.sa(a.Db,a.Dc,"oj.IntlDateTimeConverter");a.Db.Xla=new Date(1998,10,29,15,45,31);a.Db.prototype.Init=function(b){a.Db.u.Init.call(this,b)};a.b.g("IntlDateTimeConverter.prototype.Init",
{Init:a.Db.prototype.Init});a.Db.prototype.Mo=function(){this.YE||(this.YE=c.Qe());return this.YE};a.Db.prototype.format=function(b){var c=a.$a.Kl(),d=a.ga.gj(),e=this.resolvedOptions();if(null==b||"string"===typeof b&&0===a.cb.trim(""+b).length)return"";try{return this.Mo().format(b,c,e,d)}catch(h){throw b=this.dt(h,b),b;}};a.b.g("IntlDateTimeConverter.prototype.format",{format:a.Db.prototype.format});a.Db.prototype.vM=function(b,c){var d=a.$a.Kl(),e=a.ga.gj();try{return this.Mo().vM(b,d,c,e)}catch(h){throw d=
this.dt(h,b),d;}};a.b.g("IntlDateTimeConverter.prototype.formatRelative",{vM:a.Db.prototype.vM});a.Db.prototype.Pd=function(){var a=this.resolvedOptions().patternFromOptions||this.hl().pattern;return a?a.toLowerCase():""};a.b.g("IntlDateTimeConverter.prototype.getHint",{Pd:a.Db.prototype.Pd});a.Db.prototype.qJ=function(){var b="";try{b=this.format(a.Na.dateToLocalIso(a.Db.Xla))}catch(c){c instanceof a.zg&&(b="")}finally{return b}};a.Db.prototype.hl=function(){return a.Db.u.hl.call(this)};a.b.g("IntlDateTimeConverter.prototype.getOptions",
{hl:a.Db.prototype.hl});a.Db.prototype.resolvedOptions=function(){var b,c=a.ga.gj(),d=this.hl();if(c!==this.oz||!this.uE){b=a.$a.Kl();try{if(!b)return a.t.error("locale bundle for the current locale %s is unavailable",c),{};this.uE=this.Mo().resolvedOptions(b,d,c);this.oz=c}catch(e){throw b=this.dt(e),b;}}return this.uE};a.b.g("IntlDateTimeConverter.prototype.resolvedOptions",{resolvedOptions:a.Db.prototype.resolvedOptions});a.Db.prototype.CF=function(){var a=this.resolvedOptions(),b=a.hour12;return a.hour&&
!b?!0:!1};a.b.g("IntlDateTimeConverter.prototype.isHourInDaySet",{CF:a.Db.prototype.CF});a.Db.prototype.BF=function(){var a=this.resolvedOptions(),b=a.hour12;return a.hour&&b?!0:!1};a.b.g("IntlDateTimeConverter.prototype.isHourInAMPMSet",{BF:a.Db.prototype.BF});a.Db.prototype.EF=function(){return this.Ov("minute")};a.b.g("IntlDateTimeConverter.prototype.isMinuteSet",{EF:a.Db.prototype.EF});a.Db.prototype.GF=function(){return this.Ov("second")};a.b.g("IntlDateTimeConverter.prototype.isSecondSet",{GF:a.Db.prototype.GF});
a.Db.prototype.DF=function(){return this.Ov("millisecond")};a.b.g("IntlDateTimeConverter.prototype.isMilliSecondSet",{DF:a.Db.prototype.DF});a.Db.prototype.HF=function(){return this.Ov("year")};a.b.g("IntlDateTimeConverter.prototype.isYearSet",{HF:a.Db.prototype.HF});a.Db.prototype.FF=function(){return this.Ov("month")};a.b.g("IntlDateTimeConverter.prototype.isMonthSet",{FF:a.Db.prototype.FF});a.Db.prototype.AF=function(){return this.Ov("day")};a.b.g("IntlDateTimeConverter.prototype.isDaySet",{AF:a.Db.prototype.AF});
a.Db.prototype.zF=function(){return this.Ov("weekday")};a.b.g("IntlDateTimeConverter.prototype.isDayNameSet",{zF:a.Db.prototype.zF});a.Db.prototype.vt=function(b){return this.Mo().vt(b,a.$a.Kl(),a.ga.gj())};a.b.g("IntlDateTimeConverter.prototype.calculateWeek",{vt:a.Db.prototype.vt});a.Db.prototype.parse=function(b){var c,d;if(null==b||""===b)return null;var e=a.$a.Kl(),h=a.ga.gj(),f=this.resolvedOptions();try{return c=this.Mo().parse(b,e,f,h),(d=c.value)&&c.warning&&a.t.warn("The value "+b+" was leniently parsed to represent a date "+
d.toString?d.toString():d),d}catch(g){throw b=this.dt(g,b),b;}};a.b.g("IntlDateTimeConverter.prototype.parse",{parse:a.Db.prototype.parse});a.Db.prototype.xe=function(b,c){var d=a.cb.Re;if(!d(b)||!d(c))throw Error("Invalid arguments for compareISODates ",b,c);return this.Mo().xe(b,c,a.$a.Kl())};a.b.g("IntlDateTimeConverter.prototype.compareISODates",{xe:a.Db.prototype.xe});a.Db.prototype.dt=function(b,c){var d=b.errorInfo,e,h,f,g;if(d)if(e=d.errorCode,d=d.parameterMap||{},a.o.oi(d),f=d.propertyName,
b instanceof TypeError){if("optionTypesMismatch"===e||"optionTypeInvalid"===e)h=a.Na.ny(e,d)}else b instanceof RangeError?"optionOutOfRange"===e?h=a.Na.ny(e,d):"datetimeOutOfRange"===e&&(e=a.ta.F("oj-converter.datetime.datetimeOutOfRange.summary",{propertyName:f,value:d.value}),h=a.ta.F("oj-converter.datetime.datetimeOutOfRange.detail",{minValue:d.minValue,maxValue:d.maxValue}),h=new a.zg(e,h)):b instanceof SyntaxError?"optionValueInvalid"===e&&(h=a.Na.ny(e,d)):b instanceof Error&&("dateFormatMismatch"===
e?g="oj-converter.datetime.dateFormatMismatch.summary":"timeFormatMismatch"===e?g="oj-converter.datetime.timeFormatMismatch.summary":"datetimeFormatMismatch"===e?g="oj-converter.datetime.datetimeFormatMismatch.summary":"invalidTimeZoneID"===e?(e=a.ta.F("oj-converter.datetime.invalidTimeZoneID.summary",{timeZoneID:d.timeZoneID}),h=a.ta.F("oj-converter.hint.detail",{exampleValue:this.qJ()}),h=new a.zg(e,h)):"nonExistingTime"===e?g="oj-converter.datetime.nonExistingTime.summary":"missingTimeZoneData"===
e?g="oj-converter.datetime.missingTimeZoneData.summary":"dateToWeekdayMismatch"===e&&(e=a.ta.F("oj-converter.datetime.dateToWeekdayMismatch.summary",{date:d.date,weekday:d.weekday}),h=a.ta.F("oj-converter.datetime.dateToWeekdayMismatch.detail"),h=new a.zg(e,h)),g&&(e=a.ta.F(g,{value:c||d.value,format:d.format}),h=a.ta.F("oj-converter.hint.detail",{exampleValue:this.qJ()}),h=new a.zg(e,h)));h||(h=e=b.message,h=new a.zg(e,h));return h};a.Db.prototype.Ov=function(a){return this.resolvedOptions()[a]?
!0:!1};a.If=function(a){this.Init(a)};o_("IntlNumberConverter",a.If,a);a.b.sa(a.If,a.Al,"oj.IntlNumberConverter");a.If.prototype.Init=function(b){a.If.u.Init.call(this,b)};a.b.g("IntlNumberConverter.prototype.Init",{Init:a.If.prototype.Init});a.If.prototype.Mo=function(){this.YE||(this.YE=f.Qe());return this.YE};a.If.prototype.format=function(b){var c,d,e;if(null==b||"string"===typeof b&&0===a.cb.trim(""+b).length||"number"===typeof b&&isNaN(b))return"";c=a.ga.gj();d=a.$a.Kl();e=this.resolvedOptions();
try{return this.Mo().format(b,d,e,c)}catch(h){throw b=this.dt(h,b),b;}};a.b.g("IntlNumberConverter.prototype.format",{format:a.If.prototype.format});a.If.prototype.Pd=function(){return null};a.b.g("IntlNumberConverter.prototype.getHint",{Pd:a.If.prototype.Pd});a.If.prototype.hl=function(){return a.If.u.hl.call(this)};a.b.g("IntlNumberConverter.prototype.getOptions",{hl:a.If.prototype.hl});a.If.prototype.parse=function(b){var c,d,e;if(null==b||""===b)return null;c=a.ga.gj();d=a.$a.Kl();e=this.resolvedOptions();
try{return this.Mo().parse(a.cb.trim(b),d,e,c)}catch(h){throw b=this.dt(h,b),b;}};a.b.g("IntlNumberConverter.prototype.parse",{parse:a.If.prototype.parse});a.If.prototype.resolvedOptions=function(){var b;b=a.ga.gj();var c;if(b!==this.oz||!this.uE){c=a.$a.Kl();try{if(!c)return a.t.error("locale bundle for the current locale %s is unavailable",b),{};this.uE=this.Mo().resolvedOptions(c,this.hl(),b);this.oz=b}catch(d){throw b=this.dt(d),b;}}return this.uE};a.b.g("IntlNumberConverter.prototype.resolvedOptions",
{resolvedOptions:a.If.prototype.resolvedOptions});a.If.prototype.dt=function(b,c){var d,e,h=b.errorInfo,f;if(h){e=h.errorCode;h=h.parameterMap;a.o.oi(h);switch(e){case "optionTypesMismatch":case "optionTypeInvalid":d=a.Na.ny(e,h);break;case "optionOutOfRange":d=a.Na.ny(e,h);break;case "optionValueInvalid":d=a.Na.ny(e,h);break;case "decimalFormatMismatch":f="oj-converter.number.decimalFormatMismatch.summary";break;case "currencyFormatMismatch":f="oj-converter.number.currencyFormatMismatch.summary";
break;case "percentFormatMismatch":f="oj-converter.number.percentFormatMismatch.summary";break;case "unsupportedParseFormat":e=a.ta.F("oj-converter.number.decimalFormatUnsupportedParse.summary"),d=a.ta.F("oj-converter.number.decimalFormatUnsupportedParse.detail"),d=new a.zg(e,d)}f&&(e=a.ta.F(f,{value:c||h.value,format:h.format}),d=a.ta.F("oj-converter.hint.detail",{exampleValue:this.qJ()}),d=new a.zg(e,d))}d||(d=e=b.message,d=new a.zg(e,d));return d};a.If.prototype.qJ=function(){var b="";try{b=this.format(12345.98765)}catch(c){c instanceof
a.zg&&(b="",a.t.error("error retrieving hint value in format"))}finally{return b}};a.zk=function(a){this.Init(a)};o_("LengthValidator",a.zk,a);a.zk.Zc={countBy:"codeUnit"};o_("LengthValidator.defaults",a.zk.Zc,a);a.b.sa(a.zk,a.Pi,"oj.LengthValidator");a.zk.prototype.Init=function(b){var c=b.countBy;a.zk.u.Init.call(this);this.Zi=void 0!==b.min?parseInt(b.min,10):null;this.Yj=void 0!==b.max?parseInt(b.max,10):null;if(isNaN(this.Zi))throw Error("length validator's min option is not a number. min option is "+
b.min);if(isNaN(this.Yj))throw Error("length validator's max option is not a number. max option is "+b.min);if(null!==this.Zi&&0>this.Zi)throw Error("length validator's min option cannot be less than 0. min option is "+b.min);if(null!==this.Yj&&1>this.Yj)throw Error("length validator's max option cannot be less than 1. max option is "+b.max);this.kra=void 0===c?a.zk.Zc.countBy:c;b&&(this.uD=b.hint||{},this.JC=b.messageSummary||{},this.IC=b.messageDetail||{})};a.b.g("LengthValidator.prototype.Init",
{Init:a.zk.prototype.Init});a.zk.prototype.Pd=function(){var b=null,c=this.uD,d=c.exact,e=c.inRange,h=c.max,c=c.min,f=this.Yj,g=this.Zi,p=a.ta;null!==g&&null!==f?g!==f?(b={min:g,max:f},b=e?p.Nc(e,b):p.F("oj-validator.length.hint.inRange",b)):(b={length:g},b=d?p.Nc(d,b):p.F("oj-validator.length.hint.exact",b)):null!==g?(b={min:g},b=c?p.Nc(c,b):p.F("oj-validator.length.hint.min",b)):null!==f&&(b={max:f},b=h?p.Nc(h,b):p.F("oj-validator.length.hint.max",b));return b};a.zk.prototype.validate=function(b){var c=
this.IC,d=this.JC,e="",h,f=this.Yj,e=d.tooLong,d=d.tooShort,g=c.tooLong,c=c.tooShort,p=this.Zi,n;h="";var u=a.ta;n=""+b;h=this.sf(n);if((null===p||h>=this.Zi)&&(null===f||h<=this.Yj))return n;h<this.Zi?(b={value:b,min:p},h=d?u.Nc(d,b):u.F("oj-validator.length.messageSummary.tooShort"),e=c?u.Nc(c,b):u.F("oj-validator.length.messageDetail.tooShort",b)):(b={value:b,max:f},h=e?u.Nc(e,b):u.F("oj-validator.length.messageSummary.tooLong"),e=g?u.Nc(g,b):u.F("oj-validator.length.messageDetail.tooLong",b));
throw new a.Fk(h,e);};a.b.g("LengthValidator.prototype.validate",{validate:a.zk.prototype.validate});a.zk.prototype.sf=function(b){var c=b.length,d,e=0;switch(this.kra.toLowerCase()){case "codepoint":for(d=0;d<c;d++)55296===(b.charCodeAt(d)&63488)&&e++;a.o.assert(0===e%2,"the number of surrogate chars must be an even number.");b=c-e/2;break;default:b=c}return b};a.fo=function(a){this.Init(a)};o_("NumberRangeValidator",a.fo,a);a.b.sa(a.fo,a.Pi,"oj.NumberRangeValidator");a.fo.prototype.Init=function(b){a.fo.u.Init.call(this);
b&&(this.Zi=b.min,this.Yj=b.max,this.Rc=a.Na.getConverterInstance(b.converter),this.uD=b.hint||{},this.JC=b.messageSummary||{},this.IC=b.messageDetail||{})};a.b.g("NumberRangeValidator.prototype.Init",{Init:a.fo.prototype.Init});a.fo.prototype.validate=function(b){var c=b?b.toString():b,d=parseFloat(c),e=this.JC,h=this.IC,f=h.rangeOverflow,h=h.rangeUnderflow,g=e.rangeOverflow,e=e.rangeUnderflow,p=void 0!==this.Zi?parseFloat(this.Zi):null,n=void 0!==this.Yj?parseFloat(this.Yj):null,u=p&&this.Rc?this.Rc.format(p):
p,v=n&&this.Rc?this.Rc.format(n):n,w="",y="",x=null,z=a.ta;if(null===b)return b;if(null!==p&&null!==n){if(d>=p&&d<=n||p>n)return c}else if(null!==p){if(d>=p)return c}else if(null===n||d<=n)return c;null!==n&&d>n?(x={value:b,max:v},w=g?g:z.F("oj-validator.range.number.messageSummary.rangeOverflow"),y=f?z.Nc(f,x):z.F("oj-validator.range.number.messageDetail.rangeOverflow",x)):null!==p&&d<p&&(x={value:b,min:u},w=e?e:z.F("oj-validator.range.number.messageSummary.rangeUnderflow"),y=h?z.Nc(h,x):z.F("oj-validator.range.number.messageDetail.rangeUnderflow",
x));throw new a.Fk(w,y);};a.b.g("NumberRangeValidator.prototype.validate",{validate:a.fo.prototype.validate});a.fo.prototype.Pd=function(){var b=null,c=this.uD,d=c.inRange,e=c.min,c=c.max,h=a.ta,f=void 0!==this.Zi?parseFloat(this.Zi):null,g=void 0!==this.Yj?parseFloat(this.Yj):null,p=f&&this.Rc?this.Rc.format(f):f,n=g&&this.Rc?this.Rc.format(g):g;null!==f&&null!==g?b=d?h.Nc(d,{min:p,max:n}):h.F("oj-validator.range.number.hint.inRange",{min:p,max:n}):null!==f?b=e?h.Nc(e,{min:p}):h.F("oj-validator.range.number.hint.min",
{min:p}):null!==g&&(b=c?h.Nc(c,{max:n}):h.F("oj-validator.range.number.hint.max",{max:n}));return b};a.b.g("NumberRangeValidator.prototype.getHint",{Pd:a.fo.prototype.Pd});var c;c=function(){function a(){return{format:function(a,b,c,e){var h;if("number"===typeof a)h=d.dateToLocalIso(new Date(a));else if("string"===typeof a){if(h=d.trim(a),""===h)return null}else return null;if(2>=arguments.length||void 0===c)c={year:"numeric",month:"numeric",day:"numeric"};h=d.lA(h);h=s(b,c,h,e);var f=d.DM(e);void 0===
d.Mp[f]&&(f="latn");if("latn"!==f){var k,g=[];for(k=0;k<h.length;k++)"0"<=h[k]&&"9">=h[k]?g.push(d.Mp[f][h[k]]):g.push(h[k]);return g.join("")}return h},vM:function(a,b,c){return p(a,b,c)},parse:function(a,b,c,d){return q(a,b,c,d)},resolvedOptions:function(a,b,c){if(3>arguments.length||void 0===c)c=d.er(a);if(2>arguments.length||void 0===b)b={year:"numeric",month:"numeric",day:"numeric"};var e,h,f,k=d.ej(b,"OraDateTimeConverter.resolvedOptions");void 0!==b&&(h=k("isoStrFormat","string",[ma,oa,Qa,
ja,ta],ta),f=k("dst","boolean",[!0,!1],!1),e=b.timeZone);var g=d.DM(c);void 0===d.Mp[g]&&(g="latn");return void 0!==b&&void 0!==b.pattern?ua(h,e,f,c,g,b):void 0!==b?va(b,k,e,f,h,a,g,c):aa(a,c,g)},vt:function(a){a=d.isoToLocalDate(a);var b=new Date(a.getTime());b.setDate(b.getDate()+4-(b.getDay()||7));a=b.getTime();b.setMonth(0);b.setDate(1);return Math.floor(Math.round((a-b)/864E5)/7)+1},$Ma:function(a){return Ra(a)},xe:function(a,b,c){var e=xa(a,b);a=q(a,c,e,"en-US");b=q(b,c,e,"en-US");c=a.value.replace("Z",
"");b=b.value.replace("Z","");c=d.Su(c);c=Date.UTC(c[0],c[1]-1,c[2],c[3],c[4],c[5],c[6]);b=d.Su(b);b=Date.UTC(b[0],b[1]-1,b[2],b[3],b[4],b[5],b[6]);return c-b}}}var b,e,f,g,s,q,p,n,u,v,w,y,x,z,B,D={},C={},J,I,Q,A,L,G,M,F,N,Z,K,R,E,S,V,Y,O,H,T,P,da,X,U,W,ha,fa,ca,ba,aa,ga,ka,va,sa,ua,na,ya,ea,xa,Ca,Sa,Ta,za,Da,Aa,Ua,Ea,Fa,Ga,Ha,Ra,Va,Ia,Ja,Ka,wa,La,pa,qa,Wa,Ma,Na,Xa,Ya,la,Za,$a,ab,Oa=/(\d{1,4})\D+?(\d{1,4})/g,Pa=/(\d{1,4})\D+?(\d{1,4})\D+?(\d{1,4})/g,bb=/^[M][^M]|[^M]M[^M]|[^M]M$|^M$/g,jb=/^[L][^L]|[^L]L[^L]|[^L]L$|^L$/g,
cb=/^[d][^d]|[^d]d[^d]|[^d]d$|^d$|^d[^d]/,db=/(?:^|[^h])h[^h]|[^H]H[^H]|[^k]k[^k]|[^K]K[^K]|^H[^H]|^H$|[^h]h$/,eb=/'.*'/,fb=/'[^d]*d[^d]*'/,gb=/(\d{1,2})(?:\D+?(\d{1,2}))?(?:\D+?(\d{1,2}))?(?:\D+?(\d{1,3}))?/g,Ba=/h|H|K|k/g,hb=/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,ra=/ccccc|cccc|ccc|cc|c|EEEEE|EEEE|EEE|EE|E|dd|d|MMMMM|MMMM|MMM|MM|M|LLLLL|LLLL|LLL|LL|L|yyyy|yy|y|hh|h|HH|H|KK|K|kk|k|mm|m|ss|s|aa|a|SSS|SS|S|zzzz|zzz|zz|z|v|ZZZ|ZZ|Z|XXX|XX|X|VV|GGGGG|GGGG|GGG|GG|G/g,ib={0:"sun",1:"mon",2:"tue",3:"wed",4:"thu",
5:"fri",6:"sat"},ma="zulu",ja="local",ta="auto",Qa="invariant",oa="offset",ia={MMM:{token:"months",style:"format",mLen:"abbreviated",matchIndex:0,key:"month",value:"short",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},MMMM:{token:"months",style:"format",mLen:"wide",matchIndex:0,key:"month",value:"long",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},MMMMM:{token:"months",style:"format",mLen:"narrow",matchIndex:0,key:"month",value:"narrow",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},LLL:{token:"months",
style:"stand-alone",mLen:"abbreviated",matchIndex:1,key:"month",value:"short",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},LLLL:{token:"months",style:"stand-alone",mLen:"wide",matchIndex:1,key:"month",value:"long",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},LLLLL:{token:"months",style:"stand-alone",mLen:"narrow",matchIndex:1,key:"month",value:"narrow",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},E:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},
EE:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},EEE:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},EEEE:{token:"days",style:"format",dLen:"wide",matchIndex:0,key:"weekday",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},EEEEE:{token:"days",style:"format",dLen:"narrow",matchIndex:0,key:"weekday",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},c:{token:"days",style:"stand-alone",
dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},cc:{token:"days",style:"stand-alone",dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},ccc:{token:"days",style:"stand-alone",dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},cccc:{token:"days",style:"stand-alone",dLen:"wide",matchIndex:1,key:"weekday",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},ccccc:{token:"days",style:"stand-alone",
dLen:"narrow",matchIndex:1,key:"weekday",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},h:{token:"time",timePart:"hour",start1:0,end1:11,start2:1,end2:12,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},hh:{token:"time",timePart:"hour",start1:0,end1:11,start2:1,end2:12,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},K:{token:"time",timePart:"hour",start1:0,end1:11,start2:0,end2:11,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},KK:{token:"time",timePart:"hour",start1:0,end1:11,start2:0,end2:11,key:"hour",
value:"2-digit",regExp:"(\\d\\d?)"},H:{token:"time",timePart:"hour",start1:0,end1:23,start2:0,end2:23,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},HH:{token:"time",timePart:"hour",start1:0,end1:23,start2:0,end2:23,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},k:{token:"time",timePart:"hour",start1:0,end1:23,start2:1,end2:24,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},kk:{token:"time",timePart:"hour",start1:0,end1:23,start2:1,end2:24,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},m:{token:"time",
timePart:"minute",start1:0,end1:59,start2:0,end2:59,key:"minute",value:"numeric",regExp:"(\\d\\d?)"},mm:{token:"time",timePart:"minute",start1:0,end1:59,start2:0,end2:59,key:"minute",value:"2-digit",regExp:"(\\d\\d?)"},s:{token:"time",timePart:"second",start1:0,end1:59,start2:0,end2:59,key:"second",value:"numeric",regExp:"(\\d\\d?)"},ss:{token:"time",timePart:"second",start1:0,end1:59,start2:0,end2:59,key:"second",value:"2-digit",regExp:"(\\d\\d?)"},S:{token:"time",timePart:"millisec",start1:0,end1:999,
start2:0,end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},SS:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},SSS:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},d:{token:"dayOfMonth",key:"day",value:"numeric",getPartIdx:2,regExp:"(\\d\\d?)"},dd:{token:"dayOfMonth",key:"day",value:"2-digit",getPartIdx:2,regExp:"(\\d\\d?)"},M:{token:"monthIndex",
key:"month",value:"numeric",getPartIdx:1,regExp:"(\\d\\d?)"},MM:{token:"monthIndex",key:"month",value:"2-digit",getPartIdx:1,regExp:"(\\d\\d?)"},L:{token:"monthIndex",key:"month",value:"numeric",getPartIdx:1,regExp:"(\\d\\d?)"},LL:{token:"monthIndex",key:"month",value:"2-digit",getPartIdx:1,regExp:"(\\d\\d?)"},y:{token:"year",key:"year",value:"numeric",regExp:"(\\d{1,4})"},yy:{token:"year",key:"year",value:"2-digit",regExp:"(\\d\\d?)"},yyyy:{token:"year",key:"year",value:"numeric",regExp:"(\\d{1,4})"},
a:{token:"ampm",key:"hour12",value:!0,regExp:"(\\D*)"},z:{token:"tzAbbrev",regExp:"(.+?)"},v:{token:"tzAbbrev",key:"timeZoneName",value:"short",regExp:"(.+?)"},zz:{token:"tzAbbrev",regExp:"(.+?)"},zzz:{token:"tzAbbrev",regExp:"(.+?)"},zzzz:{token:"tzFull",regExp:"(.+?)"},Z:{token:"tzhm",regExp:"([+-]?\\d{1,4})"},ZZ:{token:"tzhm",regExp:"([+-]?\\d{1,4})"},ZZZ:{token:"tzhm",regExp:"([+-]?\\d{1,4})"},X:{token:"tzh",regExp:"([+-]?\\d{1,2})"},XX:{token:"tzhm",key:"XX",regExp:"([+-]?\\d{1,4})"},XXX:{token:"tzhsepm",
regExp:"([+-]?\\d{1,2}:\\d{1,2})"},VV:{token:"tzid",regExp:"(.+?)"},G:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GG:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GGG:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GGGG:{token:"era",key:"era",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},GGGGG:{token:"era",key:"era",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},"/":{token:"slash",regExp:"(\\/)"}};y=function(a){a=a["two-digit-year-start"];if(void 0===
a||isNaN(a))a=1950;return a=parseInt(a,10)};x=function(a){return"h"===a.supplemental.prefferedHours[d.Efa(d.er(a))]};J=function(a){return 0===a%400?!0:0===a%100?!1:0===a%4?!0:!1};I=function(a,b){switch(b){case 0:case 2:case 4:case 6:case 7:case 9:case 11:return 31;case 1:return J(a)?29:28;default:return 30}};B=function(a,b,c){b=d.pg(b);var e=d.ej(a,c);a=e("formatType","string",["date","time","datetime"],"date");c=e("dateFormat","string",["short","medium","long","full"],"short");var e=e("timeFormat",
"string",["short","medium","long","full"],"short"),h=b.dates.calendars.gregorian;b=h.dateFormats;var h=h.timeFormats,f,k,g;switch(c){case "full":f=b.full;break;case "long":f=b["long"];break;case "medium":f=b.medium;break;case "short":f=b["short"]}switch(e){case "full":k=h.full;break;case "long":k=h["long"];break;case "medium":k=h.medium;break;case "short":k=h["short"]}void 0===f||"datetime"!==a&&"date"!==a||(g=f);void 0===k||"datetime"!==a&&"time"!==a||(g=g?g+" "+k:k);return g};e=function(a,b){for(var c=
0,d=!1,e=0,h=a.length;e<h;e++){var f=a.charAt(e);switch(f){case "'":d?b.push("'"):c++;d=!1;break;case "\\":d&&b.push("\\");d=!d;break;default:b.push(f),d=!1}}return c};n=function(a,b,c){var d;d=void 0!==b.year||void 0!==b.month||void 0!==b.weekday||void 0!==b.day;b=void 0!==b.hour||void 0!==b.minute||void 0!==b.second;d=d&&b?"MM/dd/yy hh:mm:ss a":d?"MM/dd/yy":"hh:mm:ss a";c=new SyntaxError("Unexpected character(s) "+c+' encountered in the pattern "'+a+' An example of a valid pattern is "'+d+'".');
c.errorInfo={errorCode:"optionValueInvalid",parameterMap:{propertyName:"pattern",propertyValue:a,"propertyValueHint ":d}};throw c;};G=function(a,b,c,e){b=d.pg(b).dates.calendars.gregorian.dateTimeFormats.availableFormats;c="weekday era year month day hour minute second timeZoneName".split(" ");var h={"2-digit":0,numeric:1,narrow:2,"short":3,"long":4},f=-Infinity,k=void 0,g,l,n;for(n in b){l=!1;var m={};m.pattern=b[n];for(var t=0;null!==(g=ra.exec(n));)g=g[0],"h"!==g&&"hh"!==g||e?"H"!==g&&"HH"!==g||
!e?void 0!==ia[g]&&(m[ia[g].key]=ia[g].value):l=!0:l=!0;if(!l){for(var r in c)l=a[c[r]],g=m[c[r]],void 0===l&&void 0!==g?t-=20:void 0!==l&&void 0===g?t-=120:void 0!==l&&void 0!==g&&(l=Math.max(Math.min(h[g]-h[l],2),-2),2===l?t-=6:1===l?t-=3:-1===l?t-=6:-2===l&&(t-=8));t>f&&(f=t,k=m)}}return void 0!==k?k.pattern:null};Q=function(a,b,c){var e="",h="",f={},k={};a=d.ej(a,c);c=a("era","string",["narrow","short","long"]);e+=M(f,"era",c,{narrow:"GGGGG","short":"GGG","long":"GGGG"});c=a("year","string",["2-digit",
"numeric"]);e+=M(f,"year",c,{"2-digit":"yy",numeric:"y"});c=a("month","string",["2-digit","numeric","narrow","short","long"]);e+=M(f,"month",c,{"2-digit":"MM",numeric:"M",narrow:"MMMMM","short":"MMM","long":"MMMM"});c=a("weekday","string",["narrow","short","long"]);e+=M(f,"weekday",c,{narrow:"EEEEE","short":"E","long":"EEEE"});c=a("day","string",["2-digit","numeric"]);var e=e+M(f,"day",c,{"2-digit":"dd",numeric:"d"}),g=a("hour12","boolean",[!0,!1]);void 0===g&&(g=x(b));c=a("hour","string",["2-digit",
"numeric"]);h=!0===g?h+M(k,"hour",c,{"2-digit":"hh",numeric:"h"}):h+M(k,"hour",c,{"2-digit":"HH",numeric:"H"});c=a("minute","string",["2-digit","numeric"]);h+=M(k,"minute",c,{"2-digit":"mm",numeric:"m"});c=a("second","string",["2-digit","numeric"]);h+=M(k,"second",c,{"2-digit":"ss",numeric:"s"});c=a("timeZoneName","string",["short","long"]);h+=M(k,"timeZoneName",c,{"short":"v","long":"v"});return[e,h,f,k]};M=function(a,b,c,d){return void 0!==c?(a[b]=c,d[c]):""};A=function(a,b,c){var e=a;b=d.ej(b,
c);c=b("year","string",["2-digit","numeric"]);var h={"2-digit":"yy",numeric:"yyyy"};void 0!==c&&(e=e.replace(/y{1,4}/,h[c]));c=b("month","string",["2-digit","numeric","narrow","short","long"]);if(void 0!==c){var h={"2-digit":"MM",numeric:"M",narrow:"MMMMM","short":"MMM","long":"MMMM"},f={"2-digit":"LL",numeric:"L",narrow:"LLLLL","short":"LLL","long":"LLLL"};void 0!==h[c]&&2<h[c].length?(e=e.replace(/M{3,5}/,h[c]),e=e.replace(/L{3,5}/,f[c])):"2-digit"===c&&(bb.lastIndex=0,(c=bb.test(a))&&(e=e.replace("M",
"MM")),(c=jb.test(a))&&(e=e.replace("L","LL")))}c=b("weekday","string",["narrow","short","long"]);void 0!==c&&(e=e.replace(/E{1,5}/,{narrow:"EEEEE","short":"EEE","long":"EEEE"}[c]),e=e.replace(/c{1,5}/,{narrow:"ccccc","short":"ccc","long":"cccc"}[c]));c=b("day","string",["2-digit","numeric"]);void 0!==c&&"2-digit"===c&&(cb.lastIndex=0,fb.lastIndex=0,b=fb.test(a),c=cb.test(a),!0==c&&!1===b&&(e=e.replace("d","dd")));return e};L=function(a,b,c){var e=a;"2-digit"===d.ej(b,c)("hour","string",["2-digit",
"numeric"])&&(db.lastIndex=0,eb.lastIndex=0,b=a.replace(eb,""),b=db.exec(b),null!==b&&(Ba.lastIndex=0,e=Ba.exec(b[0]),e=a.replace(e[0],e[0]+e[0])));return e};Da=function(a,b,c){var d,e=0;for(d in b)e++;if(1<e)return null;for(d=a.length;0<d;d--)if(b=c[a.substr(0,d)],void 0!==b)return b;return a};Sa=function(a,b){var c="symbols-numberSystem-"+d.zHa(a,b);return a.numbers[c].decimal};f=function(a,b,c,e){function h(b){if(void 0!==s){var d=Sa(f,c),d=void 0===m&&void 0===t&&void 0===r?"S":"ss"+d+"SSS";b=
b.replace("ss",d);void 0===r&&(a.second=void 0)}var d=g("timeZoneName","string",["short","long"]),e={"short":"z","long":"zzzz"};void 0!==d&&(b=b.replace(/v/,e[d]));return b}var f=d.pg(b),k=d.er(b),g=d.ej(a,e),l=g("formatMatcher","string",["basic","munger"],"munger"),n=0;for(n in a)n++;0===n&&(a={year:"numeric",month:"numeric",day:"numeric"});var m,t,r,s;s=g("millisecond","string",["numeric","2-digit"]);r=g("second","string",["numeric","2-digit"]);void 0!==s&&(m=g("hour","string",["numeric","2-digit"]),
t=g("minute","string",["numeric","2-digit"]),a.second="2-digit");n=Q(a,b,e);if(void 0!==D[k]){var p=D[k].dates.calendars.gregorian.dateTimeFormats[n[0]+n[1]];if(void 0!==p)return p=h(p)}if(""===n[0]&&""===n[1])return B(a,b,e);var u=f.dates.calendars.gregorian.dateTimeFormats.availableFormats,w=u[n[0]],q=g("hour12","boolean",[!0,!1]);void 0===q&&(q=x(b));void 0===w&&""!==n[0]&&(w=Da(n[0],n[2],u),null===w&&(w=G(n[2],b,0,q)),null!==w?"basic"!==l&&(w=A(w,a,e)):w=n[0]);p=u[n[1]];void 0===p&&""!==n[1]&&
(p=Da(n[1],n[3],u),null===p&&(p=G(n[3],b,0,q)),null!==p?"basic"!==l&&(p=L(p,a,e)):p=n[1]);b=w||"";void 0!==p&&(b=""!==b?b+(" "+p):p);void 0===D[k]&&(D[k]={},D[k].dates={},D[k].dates.calendars={},D[k].dates.calendars.gregorian={},D[k].dates.calendars.gregorian.dateTimeFormats={});D[k].dates.calendars.gregorian.dateTimeFormats[n[0]+n[1]]=b;return b=h(b)};wa=function(a){a=a.split(" ");var b=a[0].split("-"),c=new Date(b[0],b[1]-1,b[2]);1<a.length&&(b=a[1].split(":"),c.setHours(b[0]),c.setMinutes(b[1]));
return c.getTime()};Ka=function(a,b,c){a=new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5]);a=a.getTime();b=b.split("/");c=c[b[0]];if(void 0===c)return null;c=c[b[1]];if(void 0===c)return null;var d=c.length,e,h,f,k,g;for(b=0;b<d;b++)if(f=c[b].usesMetazone._from,k=c[b].usesMetazone._to,g=c[b].usesMetazone._mzone,void 0===f&&void 0===k||void 0===f&&void 0!==k&&(h=wa(k),a<=h)||void 0!==f&&void 0===k&&(e=wa(f),a>=e)||void 0!==f&&void 0!==k&&(e=wa(f),h=wa(k),a>=e&&a<h))return g};La=function(a,b,c,e,h){var f=d.pg(a),
k="",g=c.timeZone;c=d.ej(c,"OraDateTimeConverter")("dst","boolean",[!0,!1],!1);if(void 0===g)return k;var l=Ka(b,g,a.supplemental.metazones),k="standard";h=h?!1:!0;a=pa(g,a);b=qa(a,b,c,h,!0);f=f.dates.timeZoneNames.metazone[l];if(void 0===f)return k=a.offset(b),d.tA("UTC",k,!0,!0);f=1===e?f["long"]:f["short"];e=a.offset(b);b=a.offset(b+1);e<b&&(k="daylight");return void 0!==f&&(k=f[k],void 0!==k)?k:d.tA("UTC",e,!0,!0)};pa=function(a,b){return h.Qe().Hga(a,b)};qa=function(a,b,c,d,e){return a.parse(Date.UTC(b[0],
b[1]-1,b[2],b[3],b[4],b[5]),c,d,e)};s=function(a,b,c,h){function k(a,b){switch(b){case 0:return a[0];case 1:return a[1];case 2:return a[2];case 3:return ib[(new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5])).getDay()]}}function g(a,b,c,e){b=k(b,c);a.push(1<e?d.uc(b,e):b)}function l(a,c,e,h,f){var k;switch(h.timePart){case "hour":k=11===h.end1?c[3]%12:c[3];"h"===f||"hh"===f?0===k&&(k=12):"k"!==f&&"kk"!==f||0!==k||(k=24);break;case "minute":k=c[4];break;case "second":k=void 0===b.second&&void 0!==b.millisecond?
0:c[5];break;case "millisec":k=c[6]}a.push(1<e?d.uc(k,e):k)}function t(b,e,h){var f,k=e.timeZone;e=q("dst","boolean",[!0,!1],!1);h=h?!1:!0;if(void 0!==k)f=pa(k,a),b=qa(f,b,e,h,!0),f=-f.offset(b);else if(c.format!==ja)switch(c.format){case oa:f=c.timeZone.split(":");b=parseInt(f[1],10);f=60*parseInt(f[0],10)+(d.nx(c.timeZone,"-")?-b:b);break;case ma:f=0;break;default:f=0}return f}var s,p=c.isoStrParts,u=0===c.dateTime.indexOf("T"),w=d.pg(a),q=d.ej(b,"OraDateTimeConverter.format");s=b.pattern||f(b,
a,h,"OraDateTimeConverter.format");h=[];var y,v=0,w=w.dates.calendars.gregorian,x=b.timeZone;for(c.format!==ja&&void 0!==x&&Ga(c,b,a);;){var z=ra.lastIndex,A=ra.exec(s),z=s.slice(z,A?A.index:s.length),v=v+e(z,h);if(!A)break;if(v%2)h.push(A[0]);else switch(y=A[0],A=y.length,z=ia[y],z.token){case "days":y=w[z.token][z.style][z.dLen];h.push(y[k(p,3)]);break;case "months":y=w[z.token][z.style][z.mLen];h.push(y[k(p,1)]);break;case "dayOfMonth":case "monthIndex":h.push(g(h,p,z.getPartIdx,A));break;case "year":y=
p[0];2===A&&(y%=100);h.push(d.uc(y,A));break;case "time":l(h,p,A,z,y);break;case "ampm":y=12>p[3]?w.dayPeriods.format.wide.am:w.dayPeriods.format.wide.pm;h.push(y);break;case "tzhm":y=t(p,b,u);0===y?"XX"===z.key?h.push("Z"):h.push("+0000"):h.push((0>=y?"-":"+")+d.uc(Math.floor(Math.abs(y/60)),2)+d.uc(Math.floor(Math.abs(y%60)),2));break;case "tzhsepm":y=t(p,b,u);0===y?h.push("Z"):h.push((0>=y?"-":"+")+d.uc(Math.floor(Math.abs(y/60)),2)+":"+d.uc(Math.floor(Math.abs(y%60)),2));break;case "tzh":y=t(p,
b,u);0===y?h.push("Z"):h.push((0>=y?"-":"+")+d.uc(Math.floor(Math.abs(y/60)),2));break;case "tzid":y=void 0!==x?x:c.format===ma?"UTC":"";h.push(y);break;case "tzAbbrev":y=La(a,p,b,0,u);h.push(y);break;case "tzFull":y=La(a,p,b,1,u);h.push(y);break;case "era":y=w.eras.eraAbbr;h.push(y["1"]);break;case "slash":h.push("/");break;default:n(s,b,y)}}return h.join("")};Z=function(a,b){return a.getFullYear()===b.getFullYear()};K=function(a,b){return 1===b.getFullYear()-a.getFullYear()};R=function(a,b){return K(b,
a)};E=function(a,b){return Z(a,b)&&a.getMonth()===b.getMonth()};S=function(a,b){return Z(a,b)?1===b.getMonth()-a.getMonth():K(a,b)?11===a.getMonth()&&0===b.getMonth():!1};V=function(a,b){return S(b,a)};F=function(a,b){var c=a.getDate(),d=b.getDate();S(a,b)&&(d+=I(a.getFullYear,a.getMonth()));return d-c};N=function(a,b){var c=a.supplemental.weekData.firstDay,e=c[d.Efa(d.er(a))];void 0===e&&(e=c["001"]);c=b-e;0>c&&(c+=7);return c};Y=function(a,b,c){if(b>c){var d=b;b=c;c=d}if(!E(b,c)&&!S(b,c))return!1;
a=F(b,c)+N(a,b.getDay());return 0<=a&&6>=a};O=function(a,b,c){if(!E(b,c)&&!S(b,c))return!1;a=F(b,c)+N(a,b.getDay());return 7<=a&&13>=a};H=function(a,b,c){return O(a,c,b)};T=function(a,b){return Z(a,b)&&E(a,b)&&a.getDate()===b.getDate()};P=function(a,b){return E(a,b)||S(a,b)?1===F(a,b):!1};da=function(a,b){return P(b,a)};Wa=function(a,b,c){var e=c.timeZone;if(d.lA(a).format===ja&&void 0===e)return a;c={gZ:"zulu"};void 0!==e&&(c.timeZone=e,c.dst=!0);a=q(a,b,c,"en-US");c={zNa:d.getLocalTimeZoneOffset(),
gZ:"local"};return q(a.value,b,c,"en-US").value};Ma=function(a,b,c){a=d.Su(a);b=d.Su(b);c?(a=Date.UTC(a[0],a[1]-1,a[2],0,0,0,0),b=Date.UTC(b[0],b[1]-1,b[2],0,0,0,0)):(a=Date.UTC(a[0],a[1]-1,a[2],a[3],a[4],a[5],a[6]),b=Date.UTC(b[0],b[1]-1,b[2],b[3],b[4],b[5],b[6]));return a-b};Na=function(a,b){return a.replace(/\{(\d+)\}/g,function(a,c){return b[c]})};Xa=function(a,b,c,e){var h,f;h={CNa:"numeric",lNa:"numeric",TMa:"numeric"};var k=d.pg(c),g=k.dates.calendars.gregorian.dateTimeFormats["long"],l=k.dates.calendars.gregorian.days.format.wide,
n=k.dates.fields;f=d.isoToLocalDate(b);var m=d.isoToLocalDate(a),k=d.lA(b);if(T(m,f))h=n.day["relative-type-0"];else if(P(m,f))h=n.day["relative-type-1"];else if(da(m,f))h=n.day["relative-type--1"];else if(f=f.getDay(),f=ib[f],a=Ma(b,a,!0),a/=864E5,-1>a&&-7<a)h=n[f]["relative-type--1"];else if(1<a&&7>a)h=l[f];else return s(c,h,k,"en-US");if(e)return h;c=s(c,{eNa:"numeric",jNa:"numeric"},k,"en-US");g=g.replace(/'/g,"");return g=Na(g,[c,h])};Ya=function(a,b,c,e){var h=d.pg(e).dates.fields;c=d.ej(c,
"OraDateTimeConverter.formatRelative")("dateField","string","day week month year hour minute second".split(" "));var f=d.isoToLocalDate(a),k=d.isoToLocalDate(b);switch(c){case "day":return T(f,k)?h.day["relative-type-0"]:P(f,k)?h.day["relative-type-1"]:da(f,k)?h.day["relative-type--1"]:la(a,b,e,"day");case "week":return Y(e,f,k)?h.week["relative-type-0"]:O(e,f,k)?h.week["relative-type-1"]:H(e,f,k)?h.week["relative-type--1"]:la(a,b,e,"week");case "month":return E(f,k)?h.month["relative-type-0"]:S(f,
k)?h.month["relative-type-1"]:V(f,k)?h.month["relative-type--1"]:la(a,b,e,"month");case "year":return Z(f,k)?h.year["relative-type-0"]:K(f,k)?h.year["relative-type-1"]:R(f,k)?h.year["relative-type--1"]:la(a,b,e,"year");case "hour":return la(a,b,e,"hour");case "minute":return la(a,b,e,"minute");case "second":return la(a,b,e,"second")}return null};ab=function(a){return 4800*a/146097};$a=function(a){var b=ab(a/864E5);return{year:Math.round(b/12),month:Math.round(b),week:Math.round(a/6048E5),day:Math.round(a/
864E5),hour:Math.round(a/36E5),minute:Math.round(a/6E4),second:Math.round(a/1E3),millisecond:a}};Za=function(a){return a.split("-")[0]};la=function(a,b,c,e){var h=Za(d.er(c)),f=c.supplemental.plurals;c=d.pg(c).dates.fields;b=Ma(b,a,!1);a=$a(Math.abs(b));null===e&&(e=46>a.second&&"second"||46>a.minute&&"minute"||23>a.hour&&"hour"||7>a.day&&"day"||4>a.week&&"week"||12>a.month&&"month"||"year");if("second"===e&&46>a.second)return c[e]["relative-type-0"];h="relativeTimePattern-count-"+f[h](a[e]);f=0>
b?"relativeTime-type-past":"relativeTime-type-future";h=c[e][f][h];void 0===h&&(h=c[e][f]["relativeTimePattern-count-other"]);return h=Na(h,[a[e]])};p=function(a,b,c){var e=d.dateToLocalIso(new Date);if("number"===typeof a)a=d.dateToLocalIso(new Date(a));else if("string"===typeof a){if(""===d.trim(a))return null}else return null;void 0===c&&(c={formatUsing:"displayName"});var h=d.ej(c,"OraDateTimeConverter.formatRelative"),f=h("relativeTime","string",["fromNow","toNow"],"fromNow"),k=h("dateField",
"string","day week month year hour minute second".split(" "));a=Wa(a,b,c);"toNow"===f&&(f=e,e=a,a=f);return"calendar"===h("formatUsing","string",["displayName","calendar"],"displayName")?(c=h("dateOnly","boolean",[!0,!1],!1),Xa(e,a,b,c)):void 0!==k?Ya(e,a,c,b):la(e,a,b,null)};Aa=function(a,b){var c;c=Error("The weekday "+a+" does not match the date "+b);c.errorInfo={errorCode:"dateToWeekdayMismatch",parameterMap:{weekday:a,date:b}};throw c;};za=function(a,b,c){var d;2===c?(d='The value "'+a+'" does not match the expected date-time format "'+
b+'"',c="datetimeFormatMismatch"):0===c?(d='The value "'+a+'" does not match the expected date format "'+b+'"',c="dateFormatMismatch"):(d='The value "'+a+'" does not match the expected time format "'+b+'"',c="timeFormatMismatch");d=Error(d);d.errorInfo={errorCode:c,parameterMap:{value:a,format:b}};throw d;};X=function(a,b){100>b&&(b+=100*Math.floor(a/100)+(b<a%100?100:0));return b};Ca=function(a,b){var c={sun:0,mon:1,tue:2,wed:3,thu:4,fri:5,sat:6},e;for(e in a)if(d.trim(d.xj(a[e]))===d.trim(b))return c[e];
return-1};Ta=function(a,b){for(var c in a)if(d.trim(d.xj(a[c]))===d.trim(b))return c-1;return-1};ba=function(a,b,c){var e=d.pg(a),h;a=e.dates.calendars.gregorian.days.format;e=e.dates.calendars.gregorian.days["stand-alone"];switch(c){case 0:h=[a.abbreviated,a.wide];break;case 1:h=[e.abbreviated,e.wide]}b=d.xj(b);c=Ca(h[0],b);-1===c&&(c=Ca(h[1],b));return c};ga=function(a,b,c){var e=-1,h=d.pg(a);a=h.dates.calendars.gregorian.months.format;h=h.dates.calendars.gregorian.months["stand-alone"];switch(c){case 0:c=
[a.wide,a.abbreviated];break;case 1:c=[h.wide,h.abbreviated];break;case 2:c=[a.wide,a.abbreviated,h.wide,h.abbreviated];break;default:return-1}b=d.xj(b);for(var f in c)if(e=Ta(c[f],b),-1!==e)break;return e};sa=function(a,b){for(var c=a.replace(hb,"\\\\$1"),d=["^"],h=[],f=0,k=0,g;null!==(g=ra.exec(c));){var l=c.slice(f,g.index),f=ra.lastIndex,k=k+e(l,d);if(k%2)d.push(g[0]);else{var l=g[0],t;void 0!==ia[l]?t=ia[l].regExp:n(a,b,l);t&&d.push(t);h.push(g[0])}}e(c.slice(f),d);d.push("$");c={regExp:d.join("").replace(/\s+/g,
"\\s+"),groups:h};return{}[a]=c};ea=function(a,b,c,d,e,h,f){if(b<c||b>d)throw b=new RangeError(e+" is out of range.  Enter a value between "+h+" and "+f+" for "+a),b.errorInfo={errorCode:"datetimeOutOfRange",parameterMap:{value:e,minValue:h,maxValue:f,propertyName:a}},b;};U=function(a,b){for(var c=0;c<a.length;c++)for(var d in a[c])if(d===b)return parseInt(c,10);return 0};ca=function(a,b,c,e,h){var f=d.pg(e).dates.calendars.gregorian.dayPeriods.format.wide.pm,k=e=gb.lastIndex=0,g=0,l=0,n=gb.exec(b);
null===n&&za(b,c,h);void 0!==n[1]&&(e=parseInt(n[1],10));void 0!==n[2]&&(k=parseInt(n[2],10));void 0!==n[3]&&(g=parseInt(n[3],10));void 0!==n[4]&&(l=parseInt(n[4],10));Ba.lastIndex=0;n=Ba.exec(c);switch(n[0]){case "h":12===e&&(e=0);ea("hour",e,0,11,e,1,12);b=d.xj(b).indexOf(d.xj(f));-1!==b&&12>e&&(e+=12);break;case "K":ea("hour",e,0,11,e,0,11);b=d.xj(b).indexOf(d.xj(f));-1!==b&&12>e&&(e+=12);break;case "H":ea("hour",e,0,23,e,0,23);break;case "k":24===e&&(e=0),ea("hour",e,0,23,e,1,24)}ea("minute",
k,0,59,k,0,59);ea("second",g,0,59,g,0,59);ea("millisec",l,0,999,l,0,999);a.setHours(e,k,g,l)};Ja=function(a,b){var c=d.pg(b),e=c.dates.calendars.gregorian.days.format,c=c.dates.calendars.gregorian.days["stand-alone"],e=[e.wide,e.abbreviated,c.wide,c.abbreviated],c=!1,h,f,k;for(f in e){for(k in e[f])if(h=e[f][k],(new RegExp(h+"\\b","i")).test(a)){c=!0;break}if(c)break;h=null}return h};ha=function(a,b,c,e,h){Pa.lastIndex=0;var f=Pa.exec(a);null===f&&za(a,b,h?2:0);var k=[{y:b.indexOf("y")},{M:b.indexOf("M")},
{d:b.indexOf("d")}];k.sort(function(a,b){for(var c in a)break;for(var d in b)break;return a[c]-b[d]});var g,l,n,m,t,r,s=U(k,"d"),p=!1,u=!1;for(r=1;3>=r;r++){var w=f[r];if(2<w.length||31<w)g=w,p=!0,m=r-1}p||(m=U(k,"y"),g=f[U(k,"y")+1]);for(r=0;3>r;r++)if(r!==m&&12<f[r+1]){n=f[r+1];u=!0;t=r;break}if(u){for(r=0;3>r;r++)if(r!==t&&r!==m){l=f[r+1];break}void 0===l&&(l=f[U(k,"M")+1])}else m===U(k,"d")?(n=f[U(k,"y")+1],l=f[U(k,"M")+1]):m===U(k,"M")?(n=f[U(k,"d")+1],l=f[U(k,"y")+1]):(n=f[U(k,"d")+1],l=f[U(k,
"M")+1]);l-=1;f=I(g,l);u&&s!==t&&12<l&&ea("month",n,0,11,n,1,12);ea("month",l,0,11,l+1,1,12);ea("day",n,1,f,n,1,f);g=X(y(c),parseInt(g,10));ea("year",g,0,9999,g,0,9999);c=new Date(g,l,n);g=Ja(a,e);null!==g&&(l=ba(e,g,0),c.getDay()!==l&&Aa(g,c.getDate()));c={value:c,offset:"",warning:"lenient parsing was used"};h&&(a=a.substr(Pa.lastIndex),0===a.length?c.value.setHours(0,0,0,0):ca(c.value,a,b,e,2));c.value=d.dateToLocalIso(c.value);return c};fa=function(a,b,c,e,h){var f=a;a=d.xj(a);var k=d.pg(e),g=
k.dates.calendars.gregorian.months.format,k=k.dates.calendars.gregorian.months["stand-alone"],g=[g.wide,g.abbreviated,k.wide,k.abbreviated],k=!1,l,n,m,t;for(n in g){l=[];for(m in g[n])t=d.xj(g[n][m]),l.push({idx:m,name:t});l.sort(function(a,b){return b.idx-a.idx});for(m in l)if(t=l[m].name,-1!==a.indexOf(t)){k=!0;a=a.replace(t,"");break}if(k)break}if(!k)return ha(f,b,c,e,h);m=ga(e,t,2);ea("month",m,0,11,m,1,12);t=Ja(f,e);n=new RegExp(t+"\\W","i");null!==t&&(a=a.replace(n,""));Oa.lastIndex=0;g=Oa.exec(a);
null===g&&za(f,b,h?2:0);f=[{y:b.indexOf("y")},{d:b.indexOf("d")}];f.sort(function(a,b){for(var c in a)break;for(var d in b)break;return a[c]-b[d]});var r,s,k=!1;for(n=1;2>=n;n++)if(l=g[n],2<l.length||31<l)r=l,k=!0,s=n-1;k||(s=U(f,"y"),r=g[U(f,"y")+1]);s=s===U(f,"d")?g[U(f,"y")+1]:g[U(f,"d")+1];r=X(y(c),parseInt(r,10));ea("year",r,0,9999,r,0,9999);c=new Date(r,m,s);null!==t&&(n=ba(e,t,0),c.getDay()!==n&&Aa(t,c.getDate()));r=I(r,m);ea("day",s,1,r,s,1,r);r={value:c,offset:"",warning:"lenient parsing was used"};
h&&(a=a.substr(Oa.lastIndex),0===a.length?r.value.setHours(0,0,0,0):ca(r.value,a,b,e,2));r.value=d.dateToLocalIso(r.value);return r};W=function(a,b,c,e){switch(v(c,"OraDateTimeConverter.parse")){case 0:return fa(a,b,c,e,!1);case 1:return c=new Date,ca(c,a,b,e,1),{value:d.dateToLocalIso(c),offset:"",warning:"lenient parsing was used"};case 2:return fa(a,b,c,e,!0)}return null};Ia=function(a,b,c,e,h,f,k,g,l,n,m){h=d.pg(a).dates.calendars.gregorian[b][h];a="months"===b?ga(a,c,f):ba(a,c,f);ea(m,a,k,g,
c,h[e][l],h[e][n]);return a};Va=function(a,b,c,d){b[c.timePart]=a;"h"===d||"hh"===d?12===a&&(b[c.timePart]=0):"k"!==d&&"kk"!==d||24!==a||(b[c.timePart]=0);ea(c.timePart,b[c.timePart],c.start1,c.end1,a,c.start2,c.end2)};g=function(a,b,c,e){var h=d.pg(e),f=h.dates.calendars.gregorian.eras.eraAbbr["1"],k=d.Qp(f);a=a.replace(f,k);var f=sa(b,c),g=(new RegExp(f.regExp)).exec(a);if(null===g)return W(a,b,c,e);for(var l=f.groups,n=null,m=null,t=null,r=null,f="",k=null,s=!1,p,u={hour:0,minute:0,second:0,millisec:0},
h=h.dates.calendars.gregorian.dayPeriods.format.wide.pm,w=y(c),q=0,v=l.length;q<v;q++){var x=g[q+1];if(x){var z=l[q],A=parseInt(x,10),C=ia[z];switch(C.token){case "months":m=Ia(e,C.token,x,C.mLen,C.style,C.matchIndex,0,11,"1","12","month name");break;case "days":p=x;r=Ia(e,C.token,x,C.dLen,C.style,C.matchIndex,0,6,"sun","sat","weekday");break;case "time":Va(A,u,C,z);break;case "dayOfMonth":t=A;if(31<t)return W(a,b,c,e);break;case "monthIndex":m=A-1;if(11<m)return W(a,b,c,e);break;case "year":n=X(w,
A);ea("year",n,0,9999,n,0,9999);break;case "ampm":s=-1!==d.xj(x).indexOf(d.xj(h));break;case "tzhm":f=x.substr(-2);f=x.substr(0,3)+":"+f;break;case "tzhsepm":f=x;break;case "tzh":f=x+":00";break;case "tzid":k=x}}}a=new Date;null===n&&(n=a.getFullYear());null===m&&null===t?(m=a.getMonth(),t=a.getDate()):null===t&&(t=1);b=I(n,m);ea("day",t,1,b,t,1,b);a.setFullYear(n,m,t);null!==r&&a.getDay()!==r&&Aa(p,a.getDate());s&&12>u.hour&&(u.hour+=12);a=[n,m+1,t,u.hour,u.minute,u.second,u.millisec];p=d.XJa(a);
null!==k&&(e=pa(k,e),f=qa(e,a,!1,!0,!0),f=-e.offset(f),f=d.tA("",f,!1,!0));""!==f&&(p+=f);return{value:p}};u=function(a,b,c){var d=c.replace(hb,"\\\\$1"),h=["^"],f=0,k=0;for(a={locale:a,numberingSystem:b,calendar:"gregorian"};null!==(b=ra.exec(d));){var g=d.slice(k,b.index),k=ra.lastIndex,f=f+e(g,h);if(!(f%2)&&(b=b[0],"/"!==b&&"zzzz"!==b&&"zzz"!==b&&"zz"!==b&&"z"!==b))if(void 0!==ia[b])if(void 0!==ia[b].key&&(a[ia[b].key]=ia[b].value),"kk"===b||"HH"===b||"H"===b||"k"===b)a.hour12=!1;else{if("KK"===
b||"hh"===b||"h"===b||"K"===b)a.hour12=!0}else n(c,a,b)}return a};z=function(a){a=u("","",a);var b=void 0!==a.hour||void 0!==a.minute||void 0!==a.second||void 0!==a.millisecond;return void 0===a.year&&void 0===a.month&&void 0===a.weekday&&void 0===a.day||!b?b?1:0:2};w=function(a){a=a.indexOf("T");return-1===a?0:0<a?2:1};v=function(a,b){if(void 0!==a.pattern)return z(a.pattern);var c=d.ej(a,b),e=void 0!==c("hour","string",["2-digit","numeric"])||void 0!==c("minute","string",["2-digit","numeric"])||
void 0!==c("second","string",["2-digit","numeric"])||void 0!==c("millisecond","string",["numeric"]),h=void 0!==c("year","string",["2-digit","numeric"])||void 0!==c("month","string",["2-digit","numeric","narrow","short","long"])||void 0!==c("day","string",["2-digit","numeric"])||void 0!==c("weekday","string",["narrow","short","long"]);if(h&&e)return 2;if(e)return 1;if(h)return 0;c=c("formatType","string",["date","time","datetime"],"date");return"datetime"===c?2:"time"===c?1:0};Ha=function(a,b){var c=
qa(a,b,!1,!0,!1),d=a.offset(c),c=a.offset(c+1);return Math.max(d,c)};Ga=function(a,b,c){var e=a.isoStrParts,h=a.format,f=b.timeZone;d.ej(b,"OraDateTimeConverter.parse");b=pa(f,c);var k;c=Date.UTC(e[0],e[1]-1,e[2],e[3],e[4],e[5]);switch(h){case oa:a=a.timeZone;k=a.split(":");h=parseInt(k[1],10);k=60*parseInt(k[0],10)+(d.nx(a,"-")?-h:h);break;case ma:k=0}a=Ha(b,e);a=b.parse(c-6E4*(a+k),!1,!0,!1);a=-b.offset(a);b=new Date(Date.UTC(e[0],e[1]-1,e[2],e[3],e[4],e[5]));k=b.getUTCMinutes()+(a-k);b.setUTCHours(b.getUTCHours()+
(k/60<<0),k%60);e[0]=b.getUTCFullYear();e[1]=b.getUTCMonth()+1;e[2]=b.getUTCDate();e[3]=b.getUTCHours();e[4]=b.getUTCMinutes();e[5]=b.getUTCSeconds()};Fa=function(a,b){var c,e="";switch(a){case 0:e=d.uc(b[0],4)+"-"+d.uc(b[1],2)+"-"+d.uc(b[2],2);break;case 1:e="T"+d.uc(b[3],2)+":"+d.uc(b[4],2)+":"+d.uc(b[5],2);c=b[6];0<c&&(e+="."+d.kO(d.uc(c,3)));break;default:e=d.uc(b[0],4)+"-"+d.uc(b[1],2)+"-"+d.uc(b[2],2)+"T"+d.uc(b[3],2)+":"+d.uc(b[4],2)+":"+d.uc(b[5],2),c=b[6],0<c&&(e+="."+d.kO(d.uc(c,3)))}return e};
Ea=function(a,b,c,e,h,f){a=pa(a,h);b=qa(a,b,c,e,f);b=a.offset(b);return d.tA("",b,!0,!0)};Ua=function(a,b,c,e){var h,f=d.ej(c,"OraDateTimeConverter.parse"),k=f("isoStrFormat","string",[ma,oa,Qa,ja,ta],ta);h=f("dst","boolean",[!0,!1],!1);var g=!0,f=b.isoStrParts,l=b.timeZone,n=c.timeZone;b=b.format;var m=c.isoStrFormat;c=Fa(a,f);if(0===a||"local"===m)return c;1===a&&(g=!1);switch(k){case oa:void 0===n&&b===oa?c+=l:void 0===n&&b===ja?c+="":void 0===n&&b===ma?c+="+00:00":void 0!==n&&(e=Ea(n,f,h,g,e,
!0),c+=e);break;case ma:k=0;void 0===n?b===oa&&(e=l.split(":"),h=parseInt(e[1],10),k=60*parseInt(e[0],10)+(d.nx(e[0],"-")?-h:h),k=-k):(e=pa(n,e),h=qa(e,f,h,g,!0),k=e=e.offset(h));0!==k&&(c=new Date(Date.UTC(f[0],f[1]-1,f[2],f[3],f[4],f[5],f[6])),k=c.getUTCMinutes()+k,c.setUTCHours(c.getUTCHours()+(k/60<<0),k%60),f[0]=c.getUTCFullYear(),f[1]=c.getUTCMonth()+1,f[2]=c.getUTCDate(),f[3]=c.getUTCHours(),f[4]=c.getUTCMinutes(),f[5]=c.getUTCSeconds(),c=Fa(a,f));c+="Z";break;case ta:void 0!==n?(e=Ea(n,f,
h,g,e,!0),c+=e):(e=l)&&(c+=e)}return c};q=function(a,b,c,e){var h=d.DM(e);void 0===d.Mp[h]&&(h="latn");if("latn"!==h){var k,l=[];for(k=0;k<a.length;k++){var n=d.Mp[h].indexOf(a[k]);-1!==n?l.push(n):l.push(a[k])}a=l.join("")}if(2>=arguments.length||void 0===c)c={year:"numeric",month:"numeric",day:"numeric"};k={};!0===d.PP.test(a)?(l=a,h=w(a)):(k=c.pattern||f(c,b,e,"OraDateTimeConverter.parse"),h=v(c,"OraDateTimeConverter.parse"),k=g(a,k,c,b),l=k.value);l=d.lA(l);void 0!==c.timeZone&&l.format!==ja&&
Ga(l,c,b);l=Ua(h,l,c,b);k.value=l;return k};xa=function(a,b){var c={isoStrFormat:ja},e=d.lA(a),h=d.lA(b).format;if(e.format===ja||h===ja)return c;c.isoStrFormat=ma;return c};ua=function(a,b,c,d,e,h){d=u(d,e,h.pattern);d.pattern=h.pattern;void 0!==a&&(d.isoStrFormat=a);void 0!==b&&(d.timeZone=b);void 0!==c&&(d.dst=c);d["two-digit-year-start"]=y(h);return d};na=function(a,b,c,d){var e=!1;void 0!==c&&(b.dst=c);c=a("year","string",["2-digit","numeric"]);void 0!==c&&(b.year=c,e=!0);c=a("era","string",
["narrow","short","long"]);void 0!==c&&(b.era=c,e=!0);c=a("month","string",["2-digit","numeric","narrow","short","long"]);void 0!==c&&(b.month=c,e=!0);c=a("day","string",["2-digit","numeric"]);void 0!==c&&(b.day=c,e=!0);c=a("weekday","string",["narrow","short","long"]);void 0!==c&&(b.weekday=c,e=!0);c=a("hour","string",["2-digit","numeric"]);void 0!==c&&(b.hour=c,e=!0,c=a("hour12","boolean",[!0,!1]),void 0===c&&(c=x(d)),b.hour12=c);c=a("minute","string",["2-digit","numeric"]);void 0!==c&&(b.minute=
c,e=!0);c=a("second","string",["2-digit","numeric"]);void 0!==c&&(b.second=c,e=!0);c=a("millisecond","string",["numeric"]);void 0!==c&&(b.millisecond=c,e=!0);return e};ka=function(a,b,d,e){b=B(b,d,c.resolvedOptions);d=e("formatType","string",["date","time","datetime"],"date");var h=e("dateFormat","string",["short","medium","long","full"],"short");e=e("timeFormat","string",["short","medium","long","full"],"short");a.formatType=d;if("datetime"===d||"date"===d)a.dateFormat=h;if("datetime"===d||"time"===
d)a.timeFormat=e;a.patternFromOptions=b};ya=function(a,b){var c=a("formatUsing","string",["displayName","calendar"]);void 0!==c&&(b.formatUsing=c);c=a("dateField","string","day week month year hour minute second".split(" "));void 0!==c&&(b.dateField=c);c=a("relativeTime","string",["fromNow","toNow"]);void 0!==c&&(b.relativeTime=c);c=a("dateOnly","boolean",[!0,!1]);void 0!==c&&(b.dateOnly=c)};va=function(a,b,c,d,e,h,k,g){k={locale:g,numberingSystem:k,calendar:"gregorian"};var l,n=0;for(l in a)n++;
if(0===n)return k.year="numeric",k.month="numeric",k.day="numeric",k;void 0!==c&&(k.timeZone=c,void 0!==e&&(k.isoStrFormat=e));ya(b,k);d=na(b,k,d,h);k["two-digit-year-start"]=y(a);if(!d)return ka(k,a,h,b),k;void 0!==c&&(l=b("timeZoneName","string",["short","long"]),void 0!==l&&(k.timeZoneName=l));k.patternFromOptions=f(k,h,g,"OraDateTimeConverter.resolvedOptions");return k};aa=function(a,b,c){a=f({year:"numeric",month:"numeric",day:"numeric"},a,b,"OraDateTimeConverter.resolvedOptions");return{calendar:"gregorian",
locale:b,numberingSystem:c,year:"numeric",month:"numeric",day:"numeric",patternFromOptions:a}};Ra=function(a){function b(c){for(var e in c){c=f.Hga(e,a);c=Ha(c,r);var h;var k=e;h=c;var g=l,s=k.split("/"),k=s[0],p=s[1],u=s="",w={},q=n[k];void 0!==q&&(s=q[p],void 0!==s&&(s=s.exemplarCity,void 0!==s&&(s=" "+s)));k=k+"/"+p;k=Ka(r,k,a.supplemental.metazones);k=g[k];void 0!==k&&void 0!==k["long"]&&(u=k["long"].generic,void 0===u&&(u=k["long"].standard),void 0!==u&&(u=" - "+u));g="(UTC)";0!==h&&(g=d.tA("UTC",
h,!0,!0),g="("+g+")");void 0===s||void 0===u?h=null:(w.offsetLocName=g+s+u,w.locName=s+u,h=w);null!==h&&(m.push({id:e,displayName:h}),t[e]=c)}}var c=d.er(a);if(void 0!==C[c]){var e=C[c].availableTimeZones;if(void 0!==e)return e}var f=h.Qe(),k={vNa:"variant"},g=d.er(a),e=d.pg(a),l=e.dates.timeZoneNames.metazone,n=e.dates.timeZoneNames.zone,m=[],t={},e=new Date,r=[e.getFullYear(),e.getMonth()+1,e.getDate(),e.getHours(),e.getMinutes(),e.getSeconds()],e=a.supplemental.timeZoneData;b(e.zones);b(e.links);
m.sort(function(a,b){return t[b.id]-t[a.id]+a.displayName.locName.localeCompare(b.displayName.locName,g,k)});for(var e=m.length,s=0;s<e;s++)m[s].displayName=m[s].displayName.offsetLocName;void 0===C[c]&&(C[c]={},C[c].availableTimeZones=m);return m};return{Qe:function(){b||(b=a());return b}}}();var d={Mp:{latn:"0123456789",arab:"\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669",thai:"\u0e50\u0e51\u0e52\u0e53\u0e54\u0e55\u0e56\u0e57\u0e58\u0e59"},jKa:/^\s+|\s+$|\u200f|\u200e/g,kKa:/\s+|\u200f|\u200e/g,
lKa:/0+$/g,yLa:["0","00","000"],PP:/^\d{4}(?:-?\d{2}(?:-?\d{2})?)?(?:T\d{2}:?\d{2}(?::?\d{2}(?:\.\d{1,3})?)?(Z|[+-]\d{2}:\d{2})?)?$|^T\d{2}:?\d{2}(?::?\d{2}(?:\.\d{1,3})?)?(Z|[+-]\d{2}:\d{2})?$/,getLocalTimeZoneOffset:function(){return d.tA("Etc/GMT",(new Date).getTimezoneOffset(),!1,!1)},J8:function(a){if(!a||"string"!==typeof a)return null;var b=d.PP.exec(a);null===b&&d.Mda(a);return void 0!==b[1]?b[1]:null},dateToLocalIso:function(a){var b=d.uc(a.getFullYear(),4)+"-"+d.uc(a.getMonth()+1,2)+"-"+
d.uc(a.getDate(),2)+"T"+d.uc(a.getHours(),2)+":"+d.uc(a.getMinutes(),2)+":"+d.uc(a.getSeconds(),2);0<a.getMilliseconds()&&(b+="."+d.kO(d.uc(a.getMilliseconds(),3)));return b},XJa:function(a){var b=d.uc(a[0],4)+"-"+d.uc(a[1],2)+"-"+d.uc(a[2],2)+"T"+d.uc(a[3],2)+":"+d.uc(a[4],2)+":"+d.uc(a[5],2);0<a[6]&&(b+="."+d.kO(d.uc(a[6],3)));return b},isoToLocalDate:function(a){return a&&"string"===typeof a?this.jza(a):null},jza:function(a){a=d.Su(a);return new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5],a[6])},Su:function(a){var b=
a.split("T"),c=a.indexOf("T");a=new Date;var e=[a.getFullYear(),a.getMonth()+1,a.getDate(),0,0,0,0];if(""!==b[0]){var h=b[0].split("-");for(a=0;a<h.length;a++)e[a]=parseInt(h[a],10)}if(-1!==c){b=b[1].split(".");c=b[0].split(":");for(a=0;a<c.length;a++)e[3+a]=parseInt(c[a],10);2===b.length&&b[1]&&(e[6]=parseInt(d.G_(b[1],3,!1),10))}return e},lA:function(a){var b={format:null,dateTime:null,timeZone:"",isoStrParts:null},c=d.PP.exec(a);null===c&&d.Mda(a);if(void 0===c[1]&&void 0===c[2])return b.format=
"local",b.dateTime=a,b.isoStrParts=d.Su(b.dateTime),b;b.timeZone=void 0!==c[1]?c[1]:c[2];b.format="Z"===b.timeZone?"zulu":"offset";b.dateTime=a.substring(0,a.indexOf(b.timeZone));b.isoStrParts=d.Su(b.dateTime);return b},KMa:function(){var a;a=Error("time zone is not supported");a.errorInfo={errorCode:"timeZoneNotSupported"};throw a;},Mda:function(a){var b;b=Error("The string "+a+" is not a valid ISO 8601 string.");b.errorInfo={errorCode:"invalidISOString",parameterMap:{isoStr:a}};throw b;},trim:function(a){return(a+
"").replace(d.jKa,"")},kO:function(a){return(a+"").replace(d.lKa,"")},Qp:function(a){return(a+"").replace(d.kKa,"")},nx:function(a,b){return 0===a.indexOf(b)},xj:function(a){return a.split("\u00a0").join(" ").toUpperCase()},uc:function(a,b){var c;c=a+"";return 1<b&&c.length<b?(c=d.yLa[b-2]+c,c.substr(c.length-b,b)):c},G_:function(a,b,c){a=""+a;var d;for(d=a.length;d<b;d+=1)a=c?"0"+a:a+"0";return a},tA:function(a,b,c,e){c=c?0<=b:0>b;b=Math.abs(b);var h=b/60<<0;b%=60;e&&(h=d.G_(h,2,!0));a=a+(c?"-":
"+")+h;if(0<b||e)a+=":"+d.G_(b,2,!0);return a},zHa:function(a,b){if(void 0===b)return"latn";var c=d.DM(b);void 0===a.numbers["symbols-numberSystem-"+c]&&(c="latn");return c},aNa:function(a){return a.split("-")[0]},Efa:function(a){a=a.split("-");return 3===a.length?a[2]:2===a.length&&2===a[1].length?a[1]:"001"},DM:function(a){a=a||"en-US";var b=a.indexOf("-u-nu-"),c="latn";-1!==b&&(c=a.substr(b+6,4));return c},dNa:function(a){var b=0,c;for(c in a)b++;return b},pg:function(a){a=a.main;var b,c;for(c in a){b=
c;break}return a[b]},er:function(a){a=a.main;var b,c;for(c in a){b=c;break}return b},zEa:function(a){if("string"===typeof a)switch(a.toLowerCase().trim()){case "true":case "1":return!0;case "false":case "0":return!1}return a},ej:function(a,b){if(void 0===a)throw Error("Internal "+b+" error. Default options missing.");return function(c,e,h,f){if(void 0!==a[c]){f=a[c];switch(e){case "boolean":f=d.zEa(f);break;case "string":f=String(f);break;case "number":f=Number(f);break;default:throw Error("Internal error. Wrong value type.");
}if(void 0!==h&&-1===h.indexOf(f)){e=[];for(f=0;f<h.length;f++)e.push(h[f]);h=new RangeError("The value '"+a[c]+"' is out of range for '"+b+"' options property '"+c+"'. Valid values: "+e);h.errorInfo={errorCode:"optionOutOfRange",parameterMap:{propertyName:c,propertyValue:a[c],propertyValueValid:e,caller:b}};throw h;}}return f}}},e={fullYear:{Er:0,du:4},month:{Er:1,du:2},date:{Er:2,du:2},hours:{Er:3,du:2},minutes:{Er:4,du:2},seconds:{Er:5,du:2},milliseconds:{Er:6,du:3},timeZone:{Er:7}};d.isoToDate=
function(a){return new Date(this._normalizeIsoString(a))};d._copyTimeOver=function(a,b){if(!a||!b)throw Error("Provided invalid arguments");b=this._normalizeIsoString(b);var c=a.indexOf("T"),d=b.indexOf("T");return b.substring(0,d)+(-1!==c?a.substring(c):"T00:00:00.000")};d._clearTime=function(a){return this._dateTime(a,{hours:0,minutes:0,seconds:0,milliseconds:0})};d._dateTime=function(a,b,c){if(!a||!b)throw Error("Invalid argument invocation");var d,h=null,f=null,f=this.uc;a=this._normalizeIsoString(a);
var q=/(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):?(\d{2})?\.?(\d{3})?(.*)?/.exec(a);if(!q)throw Error("Unable to capture anything");q=q.slice(1);if(Array.isArray(b))for(var h={},p=0,n=b.length;p<n;p++){if(f=b[p],f in e){a=e[f].Er;d=q[a];if(c&&"timeZone"===f)throw Error("Dude you tried to ask timezone to be parsed");c?(d=parseInt(d,10),h[f]=1===a?d-1:d):h[f]=d}}else if(g.isPlainObject(b)){for(p in b)c=e[p],a=c.Er,d=b[p],1===a&&"number"===typeof d&&d++,q[a]=c.du?f(d,c.du):d;h=q[0]+"-"+q[1]+"-"+q[2]+"T"+
q[3]+":"+q[4]+":"+q[5]+(6<q.length&&q[6]?"."+q[6]+(8===q.length&&q[7]?q[7]:""):"")}return h};d._normalizeIsoString=function(a){if(!a)throw Error("Provided invalid arguments");var b=(new Date).toISOString(),b=b.substring(0,b.indexOf("T")),c=a.indexOf("T"),d=-1===c?a:a.substring(0,c);-1!==c?(a=a.substring(c),a=1<a.split(":").length?a:a+":00"):a="T00:00:00.000";return(d||b)+a};var f;f=function(){function a(){return{format:function(a,b,d,e){if(2>=arguments.length||void 0===d)d={useGrouping:!0,style:"decimal"};
y(d,"OraNumberConverter.format");var h={};w(b,h,d,e);return c(a,d,b,h,e)},parse:function(a,b,c,d){if("number"===typeof a)return a;if("[object Number]"===Object.prototype.toString.call(a))return Number(a);if(2>=arguments.length||void 0===c)c={useGrouping:!0,style:"decimal"};y(c,"OraNumberConverter.parse");return e(a,b,c,d)},resolvedOptions:function(a,b,c){if(3>arguments.length||void 0===c)c=d.er(a);if(2>arguments.length||void 0===b)b={useGrouping:!0,style:"decimal"};var e=O(a,b,c);return H(e,b,c)}}}
var b,c,e,h,f,g,p,n,u,v,w,y,x,z,B,D,C,J,I,Q,A,L,G,M,F,N,Z,K,R,E,S,V,Y,O,H,T=/^[+\-]?infinity$/i,P=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/,da=/([^+-.0-9]*)([+\-]?\d*\.?\d*(E[+\-]?\d+)?).*$/,X=/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,U=/(^0\.0*)([^0].*$)/,W={trillion:[1E14,1E13,1E12],billion:[1E11,1E10,1E9],million:[1E8,1E7,1E6],thousand:[1E5,1E4,1E3]},ha={trillion:1E12,billion:1E9,million:1E6,thousand:1E3},fa={HALF_UP:"ceil",HALF_DOWN:"floor",DEFAULT:"round"};b=function(a,b,c){var d;for(d=a.length;d<b;d+=1)a=c?
"0"+a:a+"0";return a};C=function(a,b,c,d){var e=new RangeError(a+" is out of range.  Enter a value between "+b+" and "+c+" for "+d);e.errorInfo={errorCode:"numberOptionOutOfRange",parameterMap:{value:a,minValue:b,maxValue:c,propertyName:d}};throw e;};A=function(a,b,c,d,e){a=a[b];return void 0!==a?(a=Number(a),(isNaN(a)||a<c||a>d)&&C(a,c,d,b),Math.floor(a)):e};B=function(a,b){if(void 0===b)return"latn";var c=L(b);void 0===a.numbers["symbols-numberSystem-"+c]&&(c="latn");return c};D=function(a){return a.split("-")[0]};
L=function(a){a=a||"en-US";var b=a.indexOf("-u-nu-"),c="latn";-1!==b&&(c=a.substr(b+6,4));return c};w=function(a,b,c,e){var h=d.pg(a);e=B(h,e);b.numberingSystemKey=e;b.numberingSystem="symbols-numberSystem-"+e;if(void 0!==c.pattern&&0<c.pattern.length)e=c.pattern;else{switch(c.style){case "decimal":e="decimalFormats-numberSystem-";break;case "currency":e="currencyFormats-numberSystem-";break;case "percent":e="percentFormats-numberSystem-";break;default:e="decimalFormats-numberSystem-"}e+=b.numberingSystemKey;
e=h.numbers[e].standard;var f=c.decimalFormat;void 0!==f&&"decimal"===c.style&&(b.shortDecimalFormat=h.numbers["decimalFormats-numberSystem-latn"][f].decimalFormat)}f=D(d.er(a));b.plurals=a.supplemental.plurals;b.lang=f;b.pat=e;b.minusSign=h.numbers[b.numberingSystem].minusSign;b.decimalSeparator=h.numbers[b.numberingSystem].decimal;b.exponential=h.numbers[b.numberingSystem].exponential;b.groupingSeparator=h.numbers[b.numberingSystem].group;b.currencyDisplay=c.currencyDisplay;void 0!==c.currency&&
(b.currencyCode=c.currency.toUpperCase());b.style=c.style;p(c,e,h,b);void 0===c.pattern&&(b.minimumIntegerDigits=A(c,"minimumIntegerDigits",1,21,b.minimumIntegerDigits),void 0!==c.maximumFractionDigits&&(b.maximumFractionDigits=A(c,"maximumFractionDigits",0,20,b.maximumFractionDigits),b.maximumFractionDigits<b.minimumFractionDigits&&(b.minimumFractionDigits=b.maximumFractionDigits)),void 0!==c.minimumFractionDigits&&(b.minimumFractionDigits=A(c,"minimumFractionDigits",0,20,b.minimumFractionDigits)),
b.maximumFractionDigits<b.minimumFractionDigits&&(b.maximumFractionDigits=b.minimumFractionDigits))};z=function(a){var b=new TypeError('The property "currency" is required whenthe property "'+a+'" is "currency". An accepted value is a three-letter ISO 4217 currency code.');b.errorInfo={errorCode:"optionTypesMismatch",parameterMap:{propertyName:a,propertyValue:"currency",requiredPropertyName:"currency",requiredPropertyValueValid:"a three-letter ISO 4217 currency code"}};throw b;};F=function(){var a;
a=Error("long and short decimalFormats are not supported for parsing");a.errorInfo={errorCode:"unsupportedParseFormat",parameterMap:{value:"decimal"}};throw a;};y=function(a,b){var c=d.ej(a,b),e=c("style","string",["currency","decimal","percent","perMill"],"decimal");"decimal"===e&&(e=c("decimalFormat","string",["standard","short","long"]),"OraNumberConverter.parse"===b&&void 0!==e&&"standard"!==e&&F());var h=c("currency","string");"currency"===e&&void 0===h&&z("style");c("roundingMode","string",
["HALF_UP","HALF_DOWN","HALF_EVEN"],"DEFAULT")};K=function(a,b,c){function d(a){var b=0,c=0,e=0,h="";if("0"!==a[0]){for(;"0"!==a[b]&&b<a.length;)b++;h=a.substr(0,b);e=b}for(b=e;b<a.length;b++)if("0"===a[b])c++;else break;return[h,c]}var e=function(a){var b,c,d;for(b in W)for(d=W[b].length,c=0;c<d;c++)if(W[b][c]<=a)return[b,W[b][c]];return[a,null]}(a),h="";if(null!==e[1]){var h=c.plurals[c.lang](Math.floor(a/ha[e[0]])),f=""+e[1]+"-count-"+h,f=c.shortDecimalFormat[f];void 0===f&&(f=""+e[1]+"-count-other",
f=c.shortDecimalFormat[f]);var k=d(f),g=k[1],h=k[0];if(g<f.length){var l=1*Math.pow(10,g),l=e[1]/l*10;a/=l}}e="";void 0!==f&&(e=f.substr(g+k[0].length));a=N(a,b,c);return h+a+e};Z=function(a,c){var d=a+"",e=0,h=d.split(/e/i),f=h[0];U.lastIndex=0;var k=U.exec(f);null!==k?(e=k[1].length-1,f=k[2]):f=f.replace(".","");var k=1<h.length?parseInt(h[1],10):0,h=parseInt(f,10),g=c.minimumIntegerDigits+c.maximumFractionDigits;f.length>g&&(g-=f.length,h=Math.round(h*Math.pow(10,g)));g=c.minimumIntegerDigits+
c.minimumFractionDigits;h=b(h+"",g,!1);k=-1!==d.indexOf(".")?k-(c.minimumIntegerDigits-d.indexOf(".")+e):k-(g-f.length-c.minimumFractionDigits);d=Math.abs(k);d=b(d+"",c.minExponentDigits,!0);0>k&&(d=c.minusSign+d);e=h.slice(0,c.minimumIntegerDigits);return e=0<h.slice(c.minimumIntegerDigits).length?e+(c.decimalSeparator+h.slice(c.minimumIntegerDigits)+c.exponential+d):e+(c.exponential+d)};N=function(a,c,d){var e=d.groupingSize,h=d.groupingSize0,f,k=(a+"").split(/e/i),g=1<k.length?parseInt(k[1],10):
0;f=k[0];var k=f.split("."),n=1<k.length?k[1]:"";if(1<k.length&&n.length>g){var m=Math.min(d.maximumFractionDigits,n.length-g);a=J(a,m,c.roundingMode||"DEFAULT")}k=(a+"").split(/e/i);g=1<k.length?parseInt(k[1],10):0;f=k[0];k=f.split(".");f=k[0];n=1<k.length?k[1]:"";0<g?(n=b(n,g,!1),f+=n.slice(0,g),n=n.substr(g)):0>g&&(g=-g,f=b(f,g+1,!0),n=f.slice(-g,f.length)+n,f=f.slice(0,-g));n=0<m?d.decimalSeparator+(n.length>m?n.slice(0,m):b(n,m,!1)):0<d.minimumFractionDigits?d.decimalSeparator:"";n=b(n,d.decimalSeparator.length+
d.minimumFractionDigits,!1);a=d.groupingSeparator;k="";!1===c.useGrouping&&void 0===c.pattern&&(a="");f=b(f,d.minimumIntegerDigits,!0);c=f.length-1;for(n=1<n.length?n:"";0<=c;){if(0===e||e>c)return e=f.slice(0,c+1)+(k.length?a+k+n:n);k=f.slice(c-e+1,c+1)+(k.length?a+k:"");c-=e;0<h&&(e=h)}return e=f.slice(0,c+1)+a+k+n};G=function(a,b,c){if("HALF_DOWN"===c||"HALF_EVEN"===c)a=a.substr(b),a=parseInt(a,10),5<a&&(c="HALF_UP");return c};J=function(a,b,c){var d=a.toString().split(".");if(void 0===d[1])return a;
if("5"===d[1][b]&&"DEFAULT"!==c)return c=G(d[1],b,c),c=Q(d,c,b),I(a,-b,c,d);b=Math.pow(10,b);b=Math.round(a*b)/b;return isFinite(b)?b:a};Q=function(a,b,c){var d=fa[b];"HALF_EVEN"===b&&(d=0==(0===c?parseInt(a[0][a[0].length-1],10):parseInt(a[1][c-1],10))%2?fa.HALF_DOWN:fa.HALF_UP);return d};I=function(a,b,c,d){if(0===b)return"5"===d[1][0]?Math[c](a):Math.round(a);d=a.toString().split("e");a=d[0];d=d[1];a=a+"e"+(d?parseInt(d,10)-b:-b);a=parseFloat(a);a=Math[c](a);d=a.toString().split("e");a=d[0];d=
d[1];a=a+"e"+(d?parseInt(d,10)+b:b);return a=parseFloat(a)};c=function(a,b,c,e,h){c=d.pg(c);if(!isFinite(a))return Infinity===a||-Infinity===a?c.numbers[e.numberingSystem].infinity:c.numbers[e.numberingSystem].nan;c=Math.abs(a);!0===e.isPercent||"percent"===b.style?c*=100:!0===e.isPerMill&&(c*=1E3);c="decimal"===b.style&&void 0!==b.decimalFormat&&"standard"!==b.decimalFormat?K(c,b,e):!0===e.useExponentialNotation?Z(c,e):N(c,b,e);b="";b=0>a?b+(e.negativePrefix+c+e.negativeSuffix):b+(e.positivePrefix+
c+e.positiveSuffix);a=L(h);void 0===d.Mp[a]&&(a="latn");if("latn"!==a){h=[];for(e=0;e<b.length;e++)"0"<=b[e]&&"9">=b[e]?h.push(d.Mp[a][b[e]]):h.push(b[e]);return h.join("")}return b};n=function(a,b,c,e){a=d.Qp(a);var h="",f=!1,k=new RegExp("^"+e.numbers[c.numberingSystem].plusSign.replace(X,"\\$1"));a=a.replace(k,"");var g=d.Qp(c.positivePrefix),l=d.Qp(c.positiveSuffix),n=d.Qp(c.negativePrefix),k=d.Qp(c.negativeSuffix),m=new RegExp("^"+(g||"").replace(X,"\\$1")),t=new RegExp((l||"").replace(X,"\\$1")+
"$"),r=new RegExp("^"+(n||"").replace(X,"\\$1")),s=new RegExp((k||"").replace(X,"\\$1")+"$");if(!0===r.test(a)&&!0===s.test(a))a=a.replace(r,""),a=a.replace(s,""),h="-",f=!0;else if(!0===m.test(a)&&!0===t.test(a))a=a.replace(m,""),a=a.replace(t,""),h="+",f=!0;else if("currency"===b.style){b=m=c.currencyCode;var p;void 0!==e.numbers.currencies[m]&&(b=e.numbers.currencies[m].symbol);void 0===c.currencyDisplay||"symbol"===c.currencyDisplay?p=b:"code"===c.currencyDisplay&&(p=m);void 0!==p&&(m=(g||"").replace(p,
""),l=(l||"").replace(p,""),n=(n||"").replace(p,""),p=(k||"").replace(p,""),m=new RegExp(("^"+m).replace(X,"\\$1")),t=new RegExp(l.replace(X,"\\$1")+"$"),r=new RegExp(("^"+n).replace(X,"\\$1")),s=new RegExp(p.replace(X,"\\$1")+"$"),!0===r.test(a)&&!0===s.test(a)?(a=a.replace(r,""),a=a.replace(s,""),h="-",f=!0):!0===m.test(a)&&!0===t.test(a)&&(a=a.replace(m,""),a=a.replace(t,""),h="+",f=!0))}f?c=[h,a]:(c=u(a,c,e),c[2]=!0);return c};u=function(a,b,c){var e=c.numbers[b.numberingSystem].group,h=c.numbers[b.numberingSystem].decimal,
f=c.numbers[b.numberingSystem].minusSign,k="",g="";b=d.xj(c.numbers[b.numberingSystem].exponential);a=d.xj(a);a=a.split(b).join("E");a=a.split(e).join("");b=e.replace(/\u00A0/g," ");e!==b&&(a=a.split(b).join(""));a=a.split(h).join(".");"."===a.charAt(0)&&(a=a.substr(1),g=".");a=a.replace(f,"-");e=da.exec(a);g+=e[2];d.nx(g,"-")?(g=g.substr(1),k="-"):d.nx(a,"+")&&(g=g.substr(1),k="+");return[k,g]};v=function(a,b,c){var e=b.numbers[c.numberingSystem].minusSign;b=b.numbers[c.numberingSystem].plusSign;
var h;a=d.Qp(a);e=d.Qp(e);b=d.Qp(b);d.nx(a,e)?h=["-",a.substr(e.length)]:d.nx(a,d.Qp(b))&&(h=["+",a.substr(b.length)]);return h||["",a]};h=function(a,b){var c=L(b);if(void 0===d.Mp[c])return a;var e,h=[];for(e=0;e<a.length;e++){var f=d.Mp[c].indexOf(a[e]);-1!==f?h.push(f):h.push(a[e])}return h.join("")};f=function(a,b,c){var e={},h=c.numbers[b.numberingSystem].decimal;c=c.numbers[b.numberingSystem].group;a=a.replace(/ /g,"");var f=b.exponential,k=a.indexOf(f.toLowerCase());0>k&&(k=a.indexOf(d.xj(f)));
0>k?(b=a,e.exponent=null):(b=a.substr(0,k),e.exponent=a.substr(k+f.length));f=b.indexOf(h);0>f?(a=b,e.fraction=null):(a=b.substr(0,f),e.fraction=b.substr(f+h.length));a=a.split(c).join("");h=c.replace(/\u00A0/g," ");c!==h&&(a=a.split(h).join(""));e.integer=a;return e};M=function(a,b,c,e){isNaN(a)&&g(b.style,c,e);!0===c.isPercent||"percent"===b.style?a/=100:!0===c.isPerMill&&(a/=1E3);d.ej(b,"OraNumberConverter.parse")("roundDuringParse","boolean",[!0,!1],!1)&&(a=x(a,c,b));return a};g=function(a,b,
c){var d,e;d="Unparsable number "+c+" The expected number pattern is "+b.pat;switch(a){case "decimal":e="decimalFormatMismatch";break;case "currency":e="currencyFormatMismatch";break;case "percent":e="percentFormatMismatch"}a=Error(d);a.errorInfo={errorCode:e,parameterMap:{value:c,format:b.pat}};throw a;};e=function(a,b,c,e){var k=d.pg(b),g={},l=h(a,e);w(b,g,c,e);b=NaN;b=l.replace(/ /g,"");if(T.test(b))return b=parseFloat(l);e=n(l,c,g,k);b=e[0];var m=e[1];b=b||"+";if(e[2])return b=parseFloat(b+m),
M(b,c,g,a);var r=f(m,g,k);e=r.fraction;m=r.exponent;b+=r.integer;null!==e&&(b+="."+e);null!==m&&(e=v(m,k,g),b+="e"+(e[0]||"+")+e[1]);P.test(b)?b=parseFloat(b):(b=u(l,g,k),b=parseFloat(b[0]+b[1]));return M(b,c,g,a)};var ca,ba,aa,ga;Y=function(a){var b;b=new SyntaxError('Unexpected character(s) encountered in the pattern "'+a+' An example of a valid pattern is "#,##0.###".');b.errorInfo={errorCode:"optionValueInvalid",parameterMap:{propertyName:"pattern",propertyValue:a,propertyValueHint:"#,##0.###"}};
throw b;};E=function(a,b,c){return null!==(new RegExp(c,"i")).exec(a.substr(b,c.length))};V=function(a,b){var c={};null!==ca&&(b.positivePrefix=S(ca,a,b,c));null!==ba&&(b.positiveSuffix=S(ba,a,b,c));null!==aa&&(b.negativePrefix=S(aa,a,b,c));null!==ga&&(b.negativeSuffix=S(ga,a,b,c));void 0!==c.name&&(b.positiveSuffix="\u00a0"+c.name,b.positivePrefix="","ar"===b.lang?(b.negativeSuffix=a.numbers[b.numberingSystem].minusSign+"\u00a0"+c.name,b.negativePrefix=""):(b.negativeSuffix="\u00a0"+c.name,b.negativePrefix=
a.numbers[b.numberingSystem].minusSign))};S=function(a,b,c,d){for(var e="",h=0;h<a.length;){var f=a.charAt(h++);if("'"!==f){switch(f){case "\u00a4":var k=f=c.currencyCode,g=f;void 0!==b.numbers.currencies[f]&&(k=b.numbers.currencies[f].displayName,g=b.numbers.currencies[f].symbol);void 0===c.currencyDisplay||"symbol"===c.currencyDisplay?f=g:"code"!==c.currencyDisplay&&(f=k,d.name=f);break;case "%":f=b.numbers[c.numberingSystem].percentSign;break;case "\u2030":f=b.numbers[c.numberingSystem].perMille;
break;case "-":f=b.numbers[c.numberingSystem].minusSign}e=e.concat(f)}}return e};p=function(a,b,c,d){for(var e=!1,h=!1,f=0,k=0,g=!0,l=1;0<=l&&k<b.length;--l){for(var n=!1,m="",t="",r=-1,p=1,s=0,u=0,w=0,q=-1,y=-1,x,v=0,g=!0,A=k;A<b.length;++A){var C=b.charAt(A);switch(v){case 0:case 2:if(n){if("'"===C){A+1<b.length&&"'"===b.charAt(A+1)?(++A,g?m=m.concat("''"):t=t.concat("''")):n=!1;continue}}else if("#"===C||"0"===C||","===C||"."===C){v=1;--A;continue}else if("\u00a4"===C){void 0===a.currency&&z("pattern");
a.style="currency";(C=A+1<b.length&&"\u00a4"===b.charAt(A+1))&&++A;g?m=m.concat(C?"'\u00a4\u00a4":"'\u00a4"):t=t.concat(C?"'\u00a4\u00a4":"'\u00a4");continue}else if("'"===C){if("'"===C){A+1<b.length&&"'"===b.charAt(A+1)?(++A,g?m=m.concat("''"):t=t.concat("''")):n=!0;continue}}else if(";"===C){0!==v&&0!==l||Y(b);k=A+1;A=b.length;continue}else if("%"===C){a.style="percent";1!==p&&Y(b);d.isPercent=!0;p=100;g?m=m.concat("'%"):t=t.concat("'%");continue}else if("\u2030"===C){1!==p&&Y(b);a.style="perMill";
d.isPerMill=!0;p=1E3;g?m=m.concat("'\u2030"):t=t.concat("'\u2030");continue}else if("-"===C){g?m=m.concat("'-"):t=t.concat("'-");continue}g?m=m.concat(C):t=t.concat(C);break;case 1:if(1===l)++f;else{0===--f&&(v=2,g=!1);continue}if("#"===C)0<u?++w:++s,0<=q&&0>r&&++q;else if("0"===C)0<w&&Y(b),++u,0<=q&&0>r&&++q;else if(","===C)y=q,q=0;else if("."===C)0<=r&&Y(b),r=s+u+w;else if(E(b,A,"E")){h&&Y(b);h=!0;x=0;for(A+=1;A<b.length&&"0"===b.charAt(A);)++x,++f,++A;(1>s+u||1>x)&&Y(b);v=2;g=!1;--A}else v=2,g=
!1,--A,--f}}0===u&&0<s&&0<=r&&(u=r,0===u&&++u,w=s-u,s=u-1,u=1);(0>r&&0<w||0<=r&&(r<s||r>s+u)||0===q||n)&&Y(b);1===l?(ca=m,ba=t,aa=ca,ga=ba,n=s+u+w,d.minimumIntegerDigits=(0<=r?r:n)-s,d.maximumIntegerDigits=h?s+d.minimumIntegerDigits:2147483647,d.maximumFractionDigits=0<=r?n-r:0,d.minimumFractionDigits=0<=r?s+u-r:0,d.groupingSize=0<q?q:0,d.groupingSize0=y):(aa=m,ga=t,e=!0)}0===b.length&&(ca=ba="",d.minimumIntegerDigits=0,d.maximumIntegerDigits=2147483647,d.minimumFractionDigits=0,d.maximumFractionDigits=
2147483647);d.useExponentialNotation=h;d.minExponentDigits=x;if(!e||0===aa.localeCompare(ca)&&0===ga.localeCompare(ba))"currency"===a.style&&"ar"===d.lang?(ga=ba+"'\u200f-",aa=ca):(ga=ba,aa="'-"+ca);V(c,d)};x=function(a,b,c){var d=0>a;a=J(Math.abs(a),b.maximumFractionDigits,c.roundingMode||"DEFAULT");return d?-a:a};O=function(a,b,c){var e={};y(b,"OraNumberConverter.resolvedOptions");w(a,e,b,c);e.numberingSystemKey=L(c);void 0===d.Mp[e.numberingSystemKey]&&(e.numberingSystemKey="latn");return e};H=
function(a,b,c){c={locale:c,style:void 0===b.style?"decimal":b.style,useGrouping:void 0===b.useGrouping?!0:b.useGrouping,numberingSystem:a.numberingSystemKey};c.minimumIntegerDigits=a.minimumIntegerDigits;c.minimumFractionDigits=a.minimumFractionDigits;c.maximumFractionDigits=a.maximumFractionDigits;"decimal"===b.style&&void 0!==b.decimalFormat&&(c.decimalFormat=b.decimalFormat);"currency"===b.style&&(c.currency=b.currency,c.currencyDisplay=void 0===b.currencyDisplay?"symbol":b.currencyDisplay);void 0!==
b.pattern&&(c.pattern=b.pattern);a=b.roundingMode;b=b.roundDuringParse;void 0!==a&&(c.roundingMode=a);void 0!==b&&(c.roundDuringParse=b);return c};return{Qe:function(){R||(R=a());return R}}}();var h;h=function(){function a(b,c){var d=c.zones[b];if(J.test(b)){var e=0,h=b.replace(J,"").split(":"),d=60*parseInt(h[0],10);if(isNaN(d)||2===h.length&&(e=parseInt(h[1],10),isNaN(e)))return;d+=0<=d?e:-e;if(d<I||d>Q)return;d=v(d,1);d=b.replace("/etc//i","").toUpperCase()+"|"+d+"|0|"}void 0!==d&&this.OCa(u(b,
d))}function b(){return{Hga:function(a,b){var c=b.supplemental.timeZoneData;void 0===c&&C();var d=x(a,c);if(!d){var e=c.links[a];e&&(d=x(e,c))}d||B(a);return d}}}var c={},d,e,h,f,g,n,u,v,w,y,x,z,B,D,C,J=/^Etc\/GMT/i,I=-840,Q=720;w=function(a,b){for(var c=".",d="",e;0<b;)b-=1,a*=60,e=Math.floor(a+1E-6),c+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWX"[e],a-=e,e&&(d+=c,c="");return d};v=function(a,b){for(var c="",d=Math.abs(a),e=Math.floor(d),d=w(d-e,Math.min(~~b,10));0<e;)c="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWX"[e%
60]+c,e=Math.floor(e/60);0>a&&(c="-"+c);return c&&d?c+d:d||"-"!==c?c||d||"0":"0"};e=function(a){return 96<a?a-87:64<a?a-29:a-48};h=function(a){var b=0,c=a.split("."),d=c[0],c=c[1]||"",h=1,f=0,k=1;45===a.charCodeAt(0)&&(b=1,k=-1);for(;b<d.length;b++)a=e(d.charCodeAt(b)),f=60*f+a;for(b=0;b<c.length;b++)h/=60,a=e(c.charCodeAt(b)),f+=a*h;return f*k};f=function(a){for(var b=0;b<a.length;b++)a[b]=h(a[b])};g=function(a,b){for(var c=0;c<b;c++)a[c]=Math.round((a[c-1]||0)+6E4*a[c]);a[b-1]=Infinity};n=function(a,
b){var c=[],d;for(d=0;d<b.length;d++)c[d]=a[b[d]];return c};u=function(a,b){var c=b.split("|"),d=c[1].split(" "),e=c[2].split(""),h=c[3].split(" ");f(d);f(e);f(h);g(h,e.length);return{name:a,pea:n(c[0].split(" "),e),dx:n(d,e),z_:h}};B=function(a){var b;b=Error("invalid timeZone ID: "+a);b.errorInfo={errorCode:"invalidTimeZoneID",parameterMap:{timeZoneID:a}};throw b;};D=function(){var a;a=Error("The input time does not exist because it falls during the transition to daylight saving time.");a.errorInfo=
{errorCode:"nonExistingTime"};throw a;};C=function(){var a;a=Error("TimeZone data is missing. Please call require 'ojs/ojtimezonedata' in order to load the TimeZone data.");a.errorInfo={errorCode:"missingTimeZoneData"};throw a;};a.prototype={OCa:function(a){this.name=a.name;this.pea=a.pea;this.z_=a.z_;this.dx=a.dx},parse:function(a,b,c,d){var e=this.dx,h=this.z_,f=h.length-1,k,g,l,n,m,t,r;for(l=0;l<f;l++){k=e[l];g=e[l+1];r=h[l];n=r-6E4*k;m=n+36E5;t=n-36E5;if(a>=n&&a<m&&k>g)if(!0===d)D();else return l+
1;if(a>=t&&a<n&&k<g)return b?l:l+1;if(a<r-6E4*k){if(!1===c){if(b)return k<g?l:l+1;if(k<g)return l+1}return l}}return f},offset:function(a){var b=this.dx.length;return 0<=a&&a<b?parseInt(this.dx[a],10):parseInt(this.dx[b-1],10)},length:function(){return this.dx.length}};y=function(a){return(a||"").toLowerCase().replace(/\//g,"_")};z=function(b,d){var e,h;e=new a(b,d);h=y(e.name);c[h]=e};x=function(a,b){var d=y(a);void 0===c[d]&&z(a,b);return c[y(a)]||null};return{Qe:function(){d||(d=b());return d}}}();
a.Lh=function(a){this.Init(a)};o_("RegExpValidator",a.Lh,a);a.b.sa(a.Lh,a.Pi,"oj.RegExpValidator");a.Lh.yP="oj-validator.regExp.detail";a.Lh.zP="oj-validator.regExp.summary";a.Lh.prototype.Init=function(b){a.Lh.u.Init.call(this);this.Yb=b};a.b.g("RegExpValidator.prototype.Init",{Init:a.Lh.prototype.Init});a.Lh.prototype.validate=function(b){var c,d,e=this.Yb&&this.Yb.pattern||"",h;if(null===b||void 0===b||""===b)return!0;b=b||0===b?b.toString():b;var f;f=b.match("^("+e+")$");if(null===f||f[0]!==b)throw this.Yb&&
(h=this.Yb.messageSummary||null,c=this.Yb.messageDetail||null,d=this.Yb&&this.Yb.label||""),b={label:d,pattern:e,value:b},h=h?a.ta.Nc(h,b):a.ta.F(this.HT(),b),c=c?a.ta.Nc(c,b):a.ta.F(this.bT(),b),new a.Fk(h,c);return!0};a.b.g("RegExpValidator.prototype.validate",{validate:a.Lh.prototype.validate});a.Lh.prototype.Pd=function(){var b=null,c={};this.Yb&&this.Yb.hint&&(c={pattern:this.Yb.pattern},b=a.ta.Nc(this.Yb.hint,c));return b};a.b.g("RegExpValidator.prototype.getHint",{Pd:a.Lh.prototype.Pd});a.Lh.prototype.HT=
function(){return a.Lh.zP};a.Lh.prototype.bT=function(){return a.Lh.yP};a.Mh=function(a){this.Init(a)};o_("RequiredValidator",a.Mh,a);a.b.sa(a.Mh,a.Pi,"oj.RequiredValidator");a.Mh.yP="oj-validator.required.detail";a.Mh.zP="oj-validator.required.summary";a.Mh.prototype.Init=function(b){a.Mh.u.Init.call(this);this.Yb=b};a.b.g("RequiredValidator.prototype.Init",{Init:a.Mh.prototype.Init});a.Mh.prototype.validate=function(b){var c,d="",e,h={};if("number"===typeof b&&0===b||b&&0!==b.length)return!0;this.Yb&&
(c=this.Yb.messageDetail||this.Yb.message||null,e=this.Yb.messageSummary||null,d=this.Yb.label||"");h={label:d};b=e?a.ta.Nc(e,h):a.ta.F(this.HT(),h);c=c?a.ta.Nc(c,h):a.ta.F(this.bT(),h);throw new a.Fk(b,c);};a.b.g("RequiredValidator.prototype.validate",{validate:a.Mh.prototype.validate});a.Mh.prototype.Pd=function(){var b="";this.Yb&&this.Yb.hint&&(b=a.ta.F(this.Yb.hint));return b};a.b.g("RequiredValidator.prototype.getHint",{Pd:a.Mh.prototype.Pd});a.Mh.prototype.HT=function(){return a.Mh.zP};a.Mh.prototype.bT=
function(){return a.Mh.yP};a.jla=function(){return{createConverter:function(b){return new a.If(b)}}}();a.Aa.y3(a.xk.CONVERTER_TYPE_NUMBER,a.jla);a.Bka=function(){return{createConverter:function(b){return new a.Db(b)}}}();a.Aa.y3(a.xk.CONVERTER_TYPE_DATETIME,a.Bka);a.pla=function(){return{createValidator:function(b){return new a.Mh(b)}}}();a.Aa.py(a.Ve.VALIDATOR_TYPE_REQUIRED,a.pla);a.ola=function(){return{createValidator:function(b){return new a.Lh(b)}}}();a.Aa.py(a.Ve.VALIDATOR_TYPE_REGEXP,a.ola);
a.Cka=function(){return{createValidator:function(b){return new a.bo(b)}}}();a.Aa.py(a.Ve.VALIDATOR_TYPE_DATETIMERANGE,a.Cka);a.Aka=function(){return{createValidator:function(b){return new a.Hm(b)}}}();a.Aa.py(a.Ve.VALIDATOR_TYPE_DATERESTRICTION,a.Aka);a.kla=function(){return{createValidator:function(b){return new a.fo(b)}}}();a.Aa.py(a.Ve.VALIDATOR_TYPE_NUMBERRANGE,a.kla);a.Xka=function(){return{createValidator:function(b){return new a.zk(b)}}}();a.Aa.py(a.Ve.VALIDATOR_TYPE_LENGTH,a.Xka)});